// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/customer/pkg/db"

	uuid "github.com/ukama/ukama/systems/common/uuid"
)

// SimRepo is an autogenerated mock type for the SimRepo type
type SimRepo struct {
	mock.Mock
}

// Batches provides a mock function with no fields
func (_m *SimRepo) Batches() ([]db.SimBatchSnapshot, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Batches")
	}

	var r0 []db.SimBatchSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]db.SimBatchSnapshot, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []db.SimBatchSnapshot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SimBatchSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: networkId, status, page, pageSize
func (_m *SimRepo) List(networkId uuid.UUID, status string, page uint32, pageSize uint32) ([]db.SimSnapshot, int64, error) {
	ret := _m.Called(networkId, status, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.SimSnapshot
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, uint32, uint32) ([]db.SimSnapshot, int64, error)); ok {
		return rf(networkId, status, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, uint32, uint32) []db.SimSnapshot); ok {
		r0 = rf(networkId, status, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SimSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, uint32, uint32) int64); ok {
		r1 = rf(networkId, status, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, string, uint32, uint32) error); ok {
		r2 = rf(networkId, status, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolCounts provides a mock function with no fields
func (_m *SimRepo) PoolCounts() (uint32, uint32, uint32, uint32, uint32, uint32, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PoolCounts")
	}

	var r0 uint32
	var r1 uint32
	var r2 uint32
	var r3 uint32
	var r4 uint32
	var r5 uint32
	var r6 error
	if rf, ok := ret.Get(0).(func() (uint32, uint32, uint32, uint32, uint32, uint32, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func() uint32); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(uint32)
	}

	if rf, ok := ret.Get(2).(func() uint32); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(uint32)
	}

	if rf, ok := ret.Get(3).(func() uint32); ok {
		r3 = rf()
	} else {
		r3 = ret.Get(3).(uint32)
	}

	if rf, ok := ret.Get(4).(func() uint32); ok {
		r4 = rf()
	} else {
		r4 = ret.Get(4).(uint32)
	}

	if rf, ok := ret.Get(5).(func() uint32); ok {
		r5 = rf()
	} else {
		r5 = ret.Get(5).(uint32)
	}

	if rf, ok := ret.Get(6).(func() error); ok {
		r6 = rf()
	} else {
		r6 = ret.Error(6)
	}

	return r0, r1, r2, r3, r4, r5, r6
}

// NewSimRepo creates a new instance of SimRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimRepo {
	mock := &SimRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
