version: '3.3'
services:
 postgresd:
  image: postgres:13.3
  ports:
   - '5304:5432'
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Pass2020!
  networks:
   - nuru-net
  volumes:
   - postgress-data:/var/lib/postgresql

 simpool:
  image: subscriber-simpool
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@rabbitmq:5672
   - MSGCLIENT_HOST=msgclient:9095
   - SIMPOOL_SERVICE_HOST=simpool
   - SIMPOOL_SERVICE_PORT=9090
  restart: always
  networks:
   - nuru-net
  depends_on:
   - postgresd
   - msgclient

 registry:
  image: subscriber-registry
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGNAME=${ORGNAME}
   - ORGID=${ORGID}
   - QUEUE_URI=amqp://guest:guest@rabbitmq:5672
   - MSGCLIENT_HOST=msgclient:9095
   - REGISTRY_SERVICE_HOST=registry
   - REGISTRY_SERVICE_PORT=9090
   - REGISTRYHOST=http://${LOCAL_HOST_IP}:8075
  restart: always
  networks:
   - nuru-net
  depends_on:
   - postgresd
   - msgclient

 simmanager:
  image: subscriber-simmanager
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@rabbitmq:5672
   - KEY=${KEY}
   - ORGNAME=${ORGNAME}
   - ORGID=${ORGID}
   - OPERATORAGENT=http://${LOCAL_HOST_IP}:8880
   - MSGCLIENT_HOST=msgclient:9095
   - SIMMANAGER_SERVICE_HOST=simmanager
   - SIMMANAGER_SERVICE_PORT=9090
   - NOTIFICATIONHOST=http://${LOCAL_HOST_IP}:8058
   - DATAPLANHOST=http://${LOCAL_HOST_IP}:8074
   - REGISTRYHOST=http://${LOCAL_HOST_IP}:8075
  restart: always
  networks:
   - nuru-net
  depends_on:
   - postgresd
   - msgclient

 testagent:
  image: subscriber-testagent
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@rabbitmq:5672
   - MSGCLIENT_HOST=msgclient:9095
   - TESTAGENT_SERVICE_HOST=testagent
   - TESTAGENT_SERVICE_PORT=9090
  restart: always
  networks:
   - nuru-net
  depends_on:
   - postgresd
   - msgclient

 subscriber:
  image: subscriber-subscriber
  ports:
   - '8102:8080'
  restart: always
  environment:
   - BYPASS_AUTH_MODE=true
  networks:
   - nuru-net
  depends_on:
   - postgresd
   - msgclient

 msgclient:
  image: subscriber-msgclient
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@rabbitmq:5672
   - MSGCLIENT_HOST=msgclient:9095
   - SYSTEM=subscriber
  restart: always
  networks:
   - nuru-net
  depends_on:
   - postgresd

networks:
 nuru-net:
  external: true
  name: services_dev-net

volumes:
 postgress-data:
