services:

 postgresd-dummy:
  image: postgres:13.3
  ports:
   - 5463:5432
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Pass2020!
  networks:
   - ukama-net
  volumes:
   - postgress-data:/var/lib/postgresql

 dnode:
  build: ./dnode
  ports:
   - 8085:8085
  environment:
   - DEBUGMODE=true
   - ORGID=${ORGID}
   - ORGNAME=${ORGNAME}
   - AMQPCONFIG_URI=http://rabbitmq:15672
   - AMQPCONFIG_USERNAME=guest
   - AMQPCONFIG_PASSWORD=guest
  restart: always
  networks:
   - ukama-net

 dcontroller:
  build: ./dcontroller
  ports:
   - 2112:2112  
  environment:
   - DEBUGMODE=true
   - ORGID=${ORGID}
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@rabbitmq:5672
   - DCONTROLLER_SERVICE_HOST=dcontroller
   - DCONTROLLER_SERVICE_PORT=9090
   - MSGCLIENT_HOST=msgclient-dummy:9095
  restart: always
  networks:
   - ukama-net

 msgclient-dummy:
  build: ../../../systems/services/msgClient
  environment:
   - DEBUGMODE=true
   - SYSTEM=dummy
   - DB_HOST=postgresd-dummy
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - GRPC_PORT=9095
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
  restart: always
  networks:
   - ukama-net
  depends_on:
   - postgresd-dummy
   

networks:
 ukama-net:
  external: true
  name: services_ukama-net

volumes:
 postgress-data:



