// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// AuthMiddleware is an autogenerated mock type for the AuthMiddleware type
type AuthMiddleware struct {
	mock.Mock
}

// IsAuthenticated provides a mock function with given fields: c
func (_m *AuthMiddleware) IsAuthenticated(c *gin.Context) {
	_m.Called(c)
}

// IsAuthorized provides a mock function with given fields: c
func (_m *AuthMiddleware) IsAuthorized(c *gin.Context) {
	_m.Called(c)
}

// NewAuthMiddleware creates a new instance of AuthMiddleware. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthMiddleware(t testing.TB) *AuthMiddleware {
	mock := &AuthMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
