@startuml
skinparam BoxPadding 10
skinparam roundcorner 10
skinparam Shadowing false
skinparam monochrome true
skinparam ParticipantPadding 60
skinparam ActorBorderColor  Black
skinparam sequenceMessageAlign center
skinparam SequenceBoxBackgroundColor AliceBlue

actor User #Black

User -> Console: (/users)
Console -> BFF: (mutation deactivateUser)
BFF -> "Auth Registery": Validate session
BFF <-- "Auth Registery": Validate Failed
Console <-- BFF: Session Validation Failed
BFF <-- "Auth Registery": Validate success
BFF --> "User Registery": (PATCH /users/{{USER_ID}})
BFF <-- "User Registery": (PATCH /users/{{USER_ID}} response)
BFF --> Console:  (mutation deactivateUser response)

@enduml