// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	schema "github.com/ukama/ukama/systems/analytics/schema"
)

// KpiWindowReader is an autogenerated mock type for the KpiWindowReader type
type KpiWindowReader struct {
	mock.Mock
}

// WindowsInRange provides a mock function with given fields: orgID, kpiKey, fromID, toID
func (_m *KpiWindowReader) WindowsInRange(orgID string, kpiKey string, fromID int64, toID int64) ([]schema.KpiWindow, error) {
	ret := _m.Called(orgID, kpiKey, fromID, toID)

	if len(ret) == 0 {
		panic("no return value specified for WindowsInRange")
	}

	var r0 []schema.KpiWindow
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) ([]schema.KpiWindow, error)); ok {
		return rf(orgID, kpiKey, fromID, toID)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) []schema.KpiWindow); ok {
		r0 = rf(orgID, kpiKey, fromID, toID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schema.KpiWindow)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(orgID, kpiKey, fromID, toID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKpiWindowReader creates a new instance of KpiWindowReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKpiWindowReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *KpiWindowReader {
	mock := &KpiWindowReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
