// -----------------------------------------------------------------------------
// :warning: This file was automatically generated by Playwright AI Codegen.
// DO NOT MODIFY THIS FILE DIRECTLY.
// Any changes will be overwritten the next time the code is regenerated.
// -----------------------------------------------------------------------------
import { test } from '@playwright/test';

test('Onboarding Test', async ({ page }) => {
  await page.goto('http://localhost:4455/auth/login');
  await page.getByRole('textbox', { name: 'EMAIL' }).click();
  await page.getByRole('textbox', { name: 'EMAIL' }).fill('admin@ukama.com');
  await page.getByRole('textbox', { name: 'EMAIL' }).press('Tab');
  await page.getByRole('textbox', { name: 'PASSWORD' }).fill('@Pass2025.');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await page.goto('http://localhost:3000/welcome');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Network name' }).click();
  await page
    .getByRole('textbox', { name: 'Network name' })
    .fill('test-network');
  await page.getByRole('button', { name: 'NAME NETWORK' }).click();
  await page.goto(
    'http://localhost:3000/configure?step=2&step=1&networkid=4ef34602-7d97-4c8c-a19f-f0cb5eb97c38&flow=onb',
  );
  await page
    .getByRole('checkbox', { name: 'I have installed my site' })
    .check();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Retry' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Site name' }).click();
  await page.getByRole('textbox', { name: 'Site name' }).fill('test-site');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('combobox', { name: 'SWITCH' }).click();
  await page.getByRole('option', { name: 'Other' }).click();
  await page.getByRole('combobox', { name: 'POWER' }).click();
  await page.getByRole('option', { name: 'Other' }).click();
  await page.getByRole('combobox', { name: 'BACKHAUL' }).click();
  await page.getByRole('option', { name: 'Other' }).click();
  await page.getByRole('button', { name: 'Configure site' }).click();
  await page.locator('#csv-file-input-onboarding').click();
  await page
    .locator('#csv-file-input-onboarding')
    .setInputFiles('100Sims_part_4.csv');
  await page.getByRole('button', { name: 'Upload sims' }).click();
  await page.getByRole('button', { name: 'Continue to console' }).click();
});
