// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	registry "github.com/ukama/ukama/systems/services/msgClient/internal/registry"
)

// StartListener is an autogenerated mock type for the StartListener type
type StartListener struct {
	mock.Mock
}

// Execute provides a mock function with given fields: service, uri, onUnreachable
func (_m *StartListener) Execute(service string, uri string, onUnreachable func()) (registry.Listener, error) {
	ret := _m.Called(service, uri, onUnreachable)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 registry.Listener
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, func()) (registry.Listener, error)); ok {
		return rf(service, uri, onUnreachable)
	}
	if rf, ok := ret.Get(0).(func(string, string, func()) registry.Listener); ok {
		r0 = rf(service, uri, onUnreachable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(registry.Listener)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, func()) error); ok {
		r1 = rf(service, uri, onUnreachable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStartListener creates a new instance of StartListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStartListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *StartListener {
	mock := &StartListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
