// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/business/pkg/db"
)

// ActivityRepo is an autogenerated mock type for the ActivityRepo type
type ActivityRepo struct {
	mock.Mock
}

// Recent provides a mock function with given fields: limit
func (_m *ActivityRepo) Recent(limit int) ([]db.EventLog, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for Recent")
	}

	var r0 []db.EventLog
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]db.EventLog, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []db.EventLog); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.EventLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewActivityRepo creates a new instance of ActivityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepo {
	mock := &ActivityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
