// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/business/pkg/db"

	time "time"
)

// BillingRepo is an autogenerated mock type for the BillingRepo type
type BillingRepo struct {
	mock.Mock
}

// GetBillingSnapshot provides a mock function with no fields
func (_m *BillingRepo) GetBillingSnapshot() (*db.BillingSnapshot, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBillingSnapshot")
	}

	var r0 *db.BillingSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func() (*db.BillingSnapshot, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *db.BillingSnapshot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BillingSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvoiceRollups provides a mock function with given fields: from, to
func (_m *BillingRepo) InvoiceRollups(from time.Time, to time.Time) ([]db.BusinessBillingRollupDaily, error) {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for InvoiceRollups")
	}

	var r0 []db.BusinessBillingRollupDaily
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]db.BusinessBillingRollupDaily, error)); ok {
		return rf(from, to)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []db.BusinessBillingRollupDaily); ok {
		r0 = rf(from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.BusinessBillingRollupDaily)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBillingRepo creates a new instance of BillingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingRepo {
	mock := &BillingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
