// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/metrics/exporter/pb/gen"
)

// exporter is an autogenerated mock type for the exporter type
type exporter struct {
	mock.Mock
}

// Dummy provides a mock function with given fields: req
func (_m *exporter) Dummy(req *gen.DummyParameter) (*gen.DummyParameter, error) {
	ret := _m.Called(req)

	var r0 *gen.DummyParameter
	if rf, ok := ret.Get(0).(func(*gen.DummyParameter) *gen.DummyParameter); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DummyParameter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gen.DummyParameter) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewExporter interface {
	mock.TestingT
	Cleanup(func())
}

// newExporter creates a new instance of exporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newExporter(t mockConstructorTestingTnewExporter) *exporter {
	mock := &exporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
