// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/metrics/sanitizer/pb/gen"
)

// Sanitizer is an autogenerated mock type for the Sanitizer type
type Sanitizer struct {
	mock.Mock
}

// Sanitize provides a mock function with given fields: _a0
func (_m *Sanitizer) Sanitize(_a0 []byte) (*gen.SanitizeResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Sanitize")
	}

	var r0 *gen.SanitizeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*gen.SanitizeResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) *gen.SanitizeResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.SanitizeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSanitizer creates a new instance of Sanitizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSanitizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sanitizer {
	mock := &Sanitizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
