// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	pkg "github.com/ukama/ukama/systems/hub/artifactmanager/pkg"

	semver "github.com/Masterminds/semver/v3"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// GetEndpoint provides a mock function with no fields
func (_m *Storage) GetEndpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetFile provides a mock function with given fields: ctx, artifactName, artifactType, version, ext
func (_m *Storage) GetFile(ctx context.Context, artifactName string, artifactType string, version *semver.Version, ext string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, artifactName, artifactType, version, ext)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *semver.Version, string) (io.ReadCloser, error)); ok {
		return rf(ctx, artifactName, artifactType, version, ext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *semver.Version, string) io.ReadCloser); ok {
		r0 = rf(ctx, artifactName, artifactType, version, ext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *semver.Version, string) error); ok {
		r1 = rf(ctx, artifactName, artifactType, version, ext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListApps provides a mock function with given fields: ctx, artifactType
func (_m *Storage) ListApps(ctx context.Context, artifactType string) ([]string, error) {
	ret := _m.Called(ctx, artifactType)

	if len(ret) == 0 {
		panic("no return value specified for ListApps")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, artifactType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, artifactType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, artifactType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLatestPerApp provides a mock function with given fields: ctx, artifactType
func (_m *Storage) ListLatestPerApp(ctx context.Context, artifactType string) ([]pkg.AppLatest, error) {
	ret := _m.Called(ctx, artifactType)

	if len(ret) == 0 {
		panic("no return value specified for ListLatestPerApp")
	}

	var r0 []pkg.AppLatest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]pkg.AppLatest, error)); ok {
		return rf(ctx, artifactType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []pkg.AppLatest); ok {
		r0 = rf(ctx, artifactType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.AppLatest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, artifactType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVersions provides a mock function with given fields: ctx, artifactName, artifactType
func (_m *Storage) ListVersions(ctx context.Context, artifactName string, artifactType string) (*[]pkg.AritfactInfo, error) {
	ret := _m.Called(ctx, artifactName, artifactType)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 *[]pkg.AritfactInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*[]pkg.AritfactInfo, error)); ok {
		return rf(ctx, artifactName, artifactType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *[]pkg.AritfactInfo); ok {
		r0 = rf(ctx, artifactName, artifactType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]pkg.AritfactInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, artifactName, artifactType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutFile provides a mock function with given fields: ctx, artifactName, artifactType, version, ext, content, meta
func (_m *Storage) PutFile(ctx context.Context, artifactName string, artifactType string, version *semver.Version, ext string, content io.Reader, meta map[string]string) (string, error) {
	ret := _m.Called(ctx, artifactName, artifactType, version, ext, content, meta)

	if len(ret) == 0 {
		panic("no return value specified for PutFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *semver.Version, string, io.Reader, map[string]string) (string, error)); ok {
		return rf(ctx, artifactName, artifactType, version, ext, content, meta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *semver.Version, string, io.Reader, map[string]string) string); ok {
		r0 = rf(ctx, artifactName, artifactType, version, ext, content, meta)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *semver.Version, string, io.Reader, map[string]string) error); ok {
		r1 = rf(ctx, artifactName, artifactType, version, ext, content, meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatFile provides a mock function with given fields: ctx, artifactName, artifactType, version, ext
func (_m *Storage) StatFile(ctx context.Context, artifactName string, artifactType string, version *semver.Version, ext string) (bool, string, error) {
	ret := _m.Called(ctx, artifactName, artifactType, version, ext)

	if len(ret) == 0 {
		panic("no return value specified for StatFile")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *semver.Version, string) (bool, string, error)); ok {
		return rf(ctx, artifactName, artifactType, version, ext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *semver.Version, string) bool); ok {
		r0 = rf(ctx, artifactName, artifactType, version, ext)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *semver.Version, string) string); ok {
		r1 = rf(ctx, artifactName, artifactType, version, ext)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, *semver.Version, string) error); ok {
		r2 = rf(ctx, artifactName, artifactType, version, ext)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StoreBaseURL provides a mock function with given fields: artifactType
func (_m *Storage) StoreBaseURL(artifactType string) string {
	ret := _m.Called(artifactType)

	if len(ret) == 0 {
		panic("no return value specified for StoreBaseURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(artifactType)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ValidateArtifactType provides a mock function with given fields: artifactType
func (_m *Storage) ValidateArtifactType(artifactType string) error {
	ret := _m.Called(artifactType)

	if len(ret) == 0 {
		panic("no return value specified for ValidateArtifactType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(artifactType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
