// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/data-plan/package/pkg/db"
)

// PackageRepo is an autogenerated mock type for the PackageRepo type
type PackageRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: _package, nestedFunc
func (_m *PackageRepo) Add(_package *db.Package, nestedFunc ...func() error) error {
	_va := make([]interface{}, len(nestedFunc))
	for _i := range nestedFunc {
		_va[_i] = nestedFunc[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _package)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.Package, ...func() error) error); ok {
		r0 = rf(_package, nestedFunc...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: orgId, id, nestedFunc
func (_m *PackageRepo) Delete(orgId uint64, id uint64, nestedFunc ...func() error) error {
	_va := make([]interface{}, len(nestedFunc))
	for _i := range nestedFunc {
		_va[_i] = nestedFunc[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, orgId, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, ...func() error) error); ok {
		r0 = rf(orgId, id, nestedFunc...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: orgId, id
func (_m *PackageRepo) Get(orgId uint64, id uint64) ([]db.Package, error) {
	ret := _m.Called(orgId, id)

	var r0 []db.Package
	if rf, ok := ret.Get(0).(func(uint64, uint64) []db.Package); ok {
		r0 = rf(orgId, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Package)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(orgId, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: Id, pkg
func (_m *PackageRepo) Update(Id uint64, pkg db.Package) (*db.Package, error) {
	ret := _m.Called(Id, pkg)

	var r0 *db.Package
	if rf, ok := ret.Get(0).(func(uint64, db.Package) *db.Package); ok {
		r0 = rf(Id, pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Package)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, db.Package) error); ok {
		r1 = rf(Id, pkg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPackageRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewPackageRepo creates a new instance of PackageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPackageRepo(t mockConstructorTestingTNewPackageRepo) *PackageRepo {
	mock := &PackageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
