version: '3.9'
services:
 postgresd-dataplan:
  image: postgres:13.3
  ports:
   - '5303:5432'
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Pass2020!
  networks:
   - nuru-net
  volumes:
   - postgress-data:/var/lib/postgresql

 baserate:
  image: dataplan-baserate
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-dataplan
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-dataplan:9095
   - RATE_SERVICE_HOST=baserate
   - RATE_SERVICE_PORT=9090
  restart: always
  networks:
   - nuru-net
  depends_on:
   - msgclient-dataplan
   - postgresd-dataplan

 package:
  image: dataplan-package
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-dataplan
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-dataplan:9095
   - PACKAGE_SERVICE_HOST=package
   - PACKAGE_SERVICE_PORT=9090
   - ORGID=${ORGID}
  restart: always
  networks:
   - nuru-net
  depends_on:
   - baserate
   - postgresd-dataplan
   - msgclient-dataplan
 rate:
  image: dataplan-rate
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-dataplan
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-dataplan:9095
   - RATE_SERVICE_HOST=rate
   - RATE_SERVICE_PORT=9090
   - BASERATE=baserate:9090
  restart: always
  networks:
   - nuru-net
  depends_on:
   - baserate
   - postgresd-dataplan
   - msgclient-dataplan

 api-gateway:
  image: dataplan-api-gateway
  restart: always
  ports:
   - '8103:8080'
  networks:
   - nuru-net
  environment:
   - DEBUGMODE=true
   - BYPASS_AUTH_MODE=true
   # - CORS_ALLOWALLORIGINS=true
   # - CORS_ALLOWORIGINS=""
  depends_on:
   - package
   - baserate
   - rate

 msgclient-dataplan:
  image: dataplan-msgclient-dataplan
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-dataplan
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - SYSTEM=dataplan
  restart: always
  networks:
   - nuru-net
  depends_on:
   - postgresd-dataplan

networks:
 nuru-net:
  external: true
  name: services_dev-net

volumes:
 postgress-data:
