// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: pb/rates.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country  string  `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Provider *string `protobuf:"bytes,2,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	To       *int32  `protobuf:"varint,3,opt,name=to,proto3,oneof" json:"to,omitempty"`
	From     *int32  `protobuf:"varint,4,opt,name=from,proto3,oneof" json:"from,omitempty"`
}

func (x *RatesRequest) Reset() {
	*x = RatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rates_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatesRequest) ProtoMessage() {}

func (x *RatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rates_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatesRequest.ProtoReflect.Descriptor instead.
func (*RatesRequest) Descriptor() ([]byte, []int) {
	return file_pb_rates_proto_rawDescGZIP(), []int{0}
}

func (x *RatesRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RatesRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *RatesRequest) GetTo() int32 {
	if x != nil && x.To != nil {
		return *x.To
	}
	return 0
}

func (x *RatesRequest) GetFrom() int32 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

type RatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rates []*Rate `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
}

func (x *RatesResponse) Reset() {
	*x = RatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rates_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatesResponse) ProtoMessage() {}

func (x *RatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rates_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatesResponse.ProtoReflect.Descriptor instead.
func (*RatesResponse) Descriptor() ([]byte, []int) {
	return file_pb_rates_proto_rawDescGZIP(), []int{1}
}

func (x *RatesResponse) GetRates() []*Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type RateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate *Rate `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rates_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rates_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_pb_rates_proto_rawDescGZIP(), []int{2}
}

func (x *RateResponse) GetRate() *Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type RateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RateId string `protobuf:"bytes,1,opt,name=rateId,proto3" json:"rateId,omitempty"`
}

func (x *RateRequest) Reset() {
	*x = RateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rates_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRequest) ProtoMessage() {}

func (x *RateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rates_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRequest.ProtoReflect.Descriptor instead.
func (*RateRequest) Descriptor() ([]byte, []int) {
	return file_pb_rates_proto_rawDescGZIP(), []int{3}
}

func (x *RateRequest) GetRateId() string {
	if x != nil {
		return x.RateId
	}
	return ""
}

type Rate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Country     string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Network     string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Vpmn        string `protobuf:"bytes,7,opt,name=vpmn,proto3" json:"vpmn,omitempty"`
	Imsi        string `protobuf:"bytes,8,opt,name=imsi,proto3" json:"imsi,omitempty"`
	SmsMo       string `protobuf:"bytes,9,opt,name=sms_mo,json=smsMo,proto3" json:"sms_mo,omitempty"`
	SmsMt       string `protobuf:"bytes,10,opt,name=sms_mt,json=smsMt,proto3" json:"sms_mt,omitempty"`
	Data        string `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	X2G         string `protobuf:"bytes,12,opt,name=_2g,json=2g,proto3" json:"_2g,omitempty"`
	X3G         string `protobuf:"bytes,13,opt,name=_3g,json=3g,proto3" json:"_3g,omitempty"`
	X5G         string `protobuf:"bytes,20,opt,name=_5g,json=5g,proto3" json:"_5g,omitempty"`
	Lte         string `protobuf:"bytes,14,opt,name=lte,proto3" json:"lte,omitempty"`
	LteM        string `protobuf:"bytes,15,opt,name=lte_m,json=lteM,proto3" json:"lte_m,omitempty"`
	Apn         string `protobuf:"bytes,16,opt,name=apn,proto3" json:"apn,omitempty"`
	CreatedAt   string `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EffectiveAt string `protobuf:"bytes,18,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	EndAt       string `protobuf:"bytes,19,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *Rate) Reset() {
	*x = Rate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rates_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rates_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_pb_rates_proto_rawDescGZIP(), []int{4}
}

func (x *Rate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rate) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Rate) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Rate) GetVpmn() string {
	if x != nil {
		return x.Vpmn
	}
	return ""
}

func (x *Rate) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *Rate) GetSmsMo() string {
	if x != nil {
		return x.SmsMo
	}
	return ""
}

func (x *Rate) GetSmsMt() string {
	if x != nil {
		return x.SmsMt
	}
	return ""
}

func (x *Rate) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Rate) GetX2G() string {
	if x != nil {
		return x.X2G
	}
	return ""
}

func (x *Rate) GetX3G() string {
	if x != nil {
		return x.X3G
	}
	return ""
}

func (x *Rate) GetX5G() string {
	if x != nil {
		return x.X5G
	}
	return ""
}

func (x *Rate) GetLte() string {
	if x != nil {
		return x.Lte
	}
	return ""
}

func (x *Rate) GetLteM() string {
	if x != nil {
		return x.LteM
	}
	return ""
}

func (x *Rate) GetApn() string {
	if x != nil {
		return x.Apn
	}
	return ""
}

func (x *Rate) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Rate) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

func (x *Rate) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

var File_pb_rates_proto protoreflect.FileDescriptor

var file_pb_rates_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x75, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x22, 0x94, 0x01, 0x0a, 0x0c, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x02, 0x74, 0x6f, 0x88, 0x01,
	0x01, 0x12, 0x17, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x02, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x74, 0x6f, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x3b, 0x0a, 0x0d, 0x52, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x6b, 0x61, 0x6d, 0x61, 0x2e,
	0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x05, 0x72,
	0x61, 0x74, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0c, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x25,
	0x0a, 0x0b, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0xf9, 0x02, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x70, 0x6d, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x76, 0x70, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6d,
	0x73, 0x5f, 0x6d, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6d, 0x73, 0x4d,
	0x6f, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6d, 0x73, 0x5f, 0x6d, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x6d, 0x73, 0x4d, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0f, 0x0a, 0x03,
	0x5f, 0x32, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x32, 0x67, 0x12, 0x0f, 0x0a,
	0x03, 0x5f, 0x33, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x33, 0x67, 0x12, 0x0f,
	0x0a, 0x03, 0x5f, 0x35, 0x67, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x35, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x74,
	0x65, 0x12, 0x13, 0x0a, 0x05, 0x6c, 0x74, 0x65, 0x5f, 0x6d, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x74, 0x65, 0x4d, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x6e, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41,
	0x74, 0x32, 0xa1, 0x01, 0x0a, 0x0c, 0x52, 0x61, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1c,
	0x2e, 0x75, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x75,
	0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x75, 0x6b, 0x61, 0x6d, 0x61,
	0x2e, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x72, 0x61,
	0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_rates_proto_rawDescOnce sync.Once
	file_pb_rates_proto_rawDescData = file_pb_rates_proto_rawDesc
)

func file_pb_rates_proto_rawDescGZIP() []byte {
	file_pb_rates_proto_rawDescOnce.Do(func() {
		file_pb_rates_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_rates_proto_rawDescData)
	})
	return file_pb_rates_proto_rawDescData
}

var file_pb_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_rates_proto_goTypes = []interface{}{
	(*RatesRequest)(nil),  // 0: ukama.rates.v1.RatesRequest
	(*RatesResponse)(nil), // 1: ukama.rates.v1.RatesResponse
	(*RateResponse)(nil),  // 2: ukama.rates.v1.RateResponse
	(*RateRequest)(nil),   // 3: ukama.rates.v1.RateRequest
	(*Rate)(nil),          // 4: ukama.rates.v1.Rate
}
var file_pb_rates_proto_depIdxs = []int32{
	4, // 0: ukama.rates.v1.RatesResponse.rates:type_name -> ukama.rates.v1.Rate
	4, // 1: ukama.rates.v1.RateResponse.rate:type_name -> ukama.rates.v1.Rate
	0, // 2: ukama.rates.v1.RatesService.GetRates:input_type -> ukama.rates.v1.RatesRequest
	3, // 3: ukama.rates.v1.RatesService.GetRate:input_type -> ukama.rates.v1.RateRequest
	1, // 4: ukama.rates.v1.RatesService.GetRates:output_type -> ukama.rates.v1.RatesResponse
	2, // 5: ukama.rates.v1.RatesService.GetRate:output_type -> ukama.rates.v1.RateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_rates_proto_init() }
func file_pb_rates_proto_init() {
	if File_pb_rates_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_rates_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rates_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rates_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rates_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rates_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_rates_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_rates_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_rates_proto_goTypes,
		DependencyIndexes: file_pb_rates_proto_depIdxs,
		MessageInfos:      file_pb_rates_proto_msgTypes,
	}.Build()
	File_pb_rates_proto = out.File
	file_pb_rates_proto_rawDesc = nil
	file_pb_rates_proto_goTypes = nil
	file_pb_rates_proto_depIdxs = nil
}
