// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PdfClient is an autogenerated mock type for the PdfClient type
type PdfClient struct {
	mock.Mock
}

// GetPdf provides a mock function with given fields: invoiceId
func (_m *PdfClient) GetPdf(invoiceId string) ([]byte, error) {
	ret := _m.Called(invoiceId)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(invoiceId)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(invoiceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(invoiceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPdfClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewPdfClient creates a new instance of PdfClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPdfClient(t mockConstructorTestingTNewPdfClient) *PdfClient {
	mock := &PdfClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
