[build-from]
	rootfs="default"     # default is busybox minimal capp config
	contained="default"  # default namespace, cgroup, etc.

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/vendor/"
	cmd="make dhcpcd XGCCPATH=/usr/bin/"
	bin_from="/nodes/ukamaOS/distro/vendor/build/sbin/dhcpcd"
	bin_to="/sbin/"

[build-rootfs]
	mkdir="/conf/dhcpcd"

[build-conf]
        from="/nodes/ukamaOS/distro/vendor/build/etc/dhcpcd.conf"
        to="/conf/config.file"

# Following are use to create config.json file which is used by starter.d to start 
# the capp within ukamaOS and pkg everything
[capp-exec]
	name="dhcpcd"
	version="latest"
	bin="dhcpcd"
	path="/sbin/" # path where the exec should be. Mathches build.bin_to
	args="--config /ukama/configs/dhcpcd/config.file"

	
# Final output format for capp
[capp-output]
	format="tar.gz"
