[build-from]
	rootfs="default"     # default is busybox minimal capp config
	contained="default"  # default namespace, cgroup, etc.

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/system/example"
	cmd="make"
	bin_from="/nodes/ukamaOS/distro/system/example/example.d"
	bin_to="/sbin"

[build-rootfs]
	mkdir="/ukama/conf/example"

[build-conf]
        from="/nodes/configs/capps/example/config.file"
        to="/ukama/conf/example/config.file"

# Following are use to create config.json file which is used by starter.d to start 
# the capp within ukamaOS and pkg everything
[capp-exec]
	name="example"
	version="latest"
	bin="example.d"
	path="/sbin" # path where the exec should be. Mathches build.bin_to
	args="-f /ukama/conf/example/config.file"
	envs="key1=value1"
	
# Final output format for capp
[capp-output]
	format="tar.gz"

# Nothing to see here. Move on.
