[build-from]
	rootfs="default"     # default is busybox minimal capp config
	contained="default"  # default namespace, cgroup, etc.

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/system/mesh"
	cmd="make XGCCPATH=/usr/bin/"
	bin_from="/nodes/ukamaOS/distro/system/mesh/mesh.d"
	bin_to="/sbin/"

[build-rootfs]
	mkdir="/ukama/conf/mesh"

[build-conf]
        from="/nodes/configs/capps/mesh/config.toml"
        to="/ukama/conf/mesh/config.toml"

[build-misc]
	from="/nodes/configs/capps/mesh/ip_file"
	to="/ukama/conf/mesh/ip_file"

# Following are use to create config.json file which is used by lxce.d to start 
# the capp within ukamaOS and pkg everything
[capp-exec]
	name="meshd"
	version="latest"
	bin="mesh.d"
	path="/sbin/" # path where the exec should be. Mathches build.bin_to
	args="--config /ukama/conf/mesh/config.toml"
	
# Final output format for capp
[capp-output]
	format="tar.gz"

# Nothing to see here. Move on.
