[build-from]
	rootfs="default"     # default is busybox minimal capp config
	contained="default"  # default namespace, cgroup, etc.

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/system/starterd"
	cmd="make"
	bin_from="/nodes/ukamaOS/distro/system/starterd/starter.d"
	bin_to="/sbin"

[build-rootfs]
	mkdir="/ukama/conf"

[build-conf]
    from="/nodes/manifest.json"
    to="/manifest.json"

# Following are use to create config.json file which is used by starter.d to start 
# the capp within ukamaOS and pkg everything
[capp-exec]
	name="starterd"
	version="latest"
	bin="starter.d"
	path="/sbin" # path where the exec should be. Mathches build.bin_to
	args="--manifest-file /manifest.file"
	
# Final output format for capp
[capp-output]
	format="tar.gz"

# Nothing to see here. Move on.
