[build-from]
	rootfs="default"     # default is busybox minimal capp config
	contained="default"  # default namespace, cgroup, etc.

[build-compile]
	version="0.1"
	static="false"
	source="/home/kashif/work/ukama/ukamaOS/distro/vendor/sysctl"
	cmd="make"
	bin_from="/home/kashif/work/ukama/ukamaOS/distro/vendor/sysctl/sysctl"
	bin_to="/sbin/"

[build-rootfs]
	mkdir="/ukama/configs/sysctl /proc/sys"

[build-conf]
        from="/home/kashif/work/ukama/ukamaOS/distro/vendor/sysctl/00-linuxkit.conf"
        to="/ukama/configs/sysctl/config.file"

# Following are use to create config.json file which is used by starter.d to start 
# the capp within ukamaOS and pkg everything
[capp-exec]
	name="sysctl"
	version="latest"
	bin="sysctl"
	path="/sbin/" # path where the exec should be. Mathches build.bin_to
	args="-configDir /ukama/configs/sysctl/config.file"

# Final output format for capp
[capp-output]
	format="tar.gz"
