// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/testing/services/dummy/dsimfactory/pkg/db"
)

// SimRepo is an autogenerated mock type for the SimRepo type
type SimRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: sims
func (_m *SimRepo) Add(sims []db.Sim) error {
	ret := _m.Called(sims)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]db.Sim) error); ok {
		r0 = rf(sims)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByIccid provides a mock function with given fields: iccid
func (_m *SimRepo) GetByIccid(iccid string) (*db.Sim, error) {
	ret := _m.Called(iccid)

	if len(ret) == 0 {
		panic("no return value specified for GetByIccid")
	}

	var r0 *db.Sim
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.Sim, error)); ok {
		return rf(iccid)
	}
	if rf, ok := ret.Get(0).(func(string) *db.Sim); ok {
		r0 = rf(iccid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Sim)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iccid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSims provides a mock function with no fields
func (_m *SimRepo) GetSims() ([]db.Sim, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSims")
	}

	var r0 []db.Sim
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]db.Sim, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []db.Sim); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Sim)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSimRepo creates a new instance of SimRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimRepo {
	mock := &SimRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
