version: '3.3'
services:
 postgresd-node:
  image: postgres:13.3
  ports:
   - 5489:5432
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Pass2020!
  networks:
   - ukama-net
  volumes:
   - postgress-data:/var/lib/postgresql

 controller:
  build: ./controller
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - CONTROLLER_SERVICE_HOST=controller
   - CONTROLLER_SERVICE_PORT=9090
   - ORGNAME=ukama
   - HTTP_INITCLIENT=http://api-gateway-init:8080
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-node
   - postgresd-node
   - operation-monitor


 site-controller:
  build: ./site-controller
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - SITE_CONTROLLER_SERVICE_HOST=site-controller
   - SITE_CONTROLLER_SERVICE_PORT=9090
   - ORGNAME=ukama
   - HTTP_INITCLIENT=http://api-gateway-init:8080
  restart: always
  networks:
   - ukama-net
  depends_on:
   - controller
   - msgclient-node
   - postgresd-node

 health:
  build: ./health
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - HEALTH_SERVICE_HOST=health
   - HEALTH_SERVICE_PORT=9090
   - ORGNAME=ukama
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-node

 software:
  build: ./software
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - SOFTWARE_SERVICE_HOST=software
   - SOFTWARE_SERVICE_PORT=9090
   - ORGNAME=ukama
   - WIMSI_HOST=http://192.168.0.138:8080
   - NODEGWIPS='["123", "1.1.1.1"]'
   - OPERATION_MANAGERHOST=manager:9090
   - OPERATION_MONITORHOST=operation-monitor:9090
   - OPERATION_LEASESECS=1800
   - OPERATION_DEADLINESECS=1800
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-node

 state:
  build: ./state
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - STATE_SERVICE_HOST=state
   - STATE_SERVICE_PORT=9090
   - ORGNAME=ukama
   - ORGID=fbc2a80d-339e-4d3c-acaa-329dd3d1b221
   - CONFIGPATH=/app/pkg/nodeState.json
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-node

 notify:
  build: ./notify
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - NOTIFY_SERVICE_HOST=notify
   - NOTIFY_SERVICE_PORT=9090
   - ORGNAME=ukama
  restart: always
  networks:
   - ukama-net
  depends_on:
   - postgresd-node

 operation-monitor:
  build: ./operation-monitor
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - OPERATIONMONITOR_SERVICE_HOST=operation-monitor
   - OPERATIONMONITOR_SERVICE_PORT=9090
   - ORGNAME=ukama
   - ORGID=fbc2a80d-339e-4d3c-acaa-329dd3d1b221
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-node
   - postgresd-node

 node-gateway-node:
  build: ./node-gateway
  restart: always
  ports:
   - 8036:8080
  networks:
   - ukama-net
  environment:
   - DEBUGMODE=true
   - BYPASS_AUTH_MODE=true
  depends_on:
   - health
   - postgresd-node
   - initclient-node

 api-gateway-node:
  build: ./api-gateway
  restart: always
  ports:
   - 8097:8080
  networks:
   - ukama-net
  environment:
   - DEBUGMODE=true
   - BYPASS_AUTH_MODE=true
  depends_on:
   - controller
   - site-controller
   - postgresd-node
   - initclient-node

 msgclient-node:
  build: ../services/msgClient
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - GRPC_PORT=9095
   - SYSTEM=node
  restart: always
  networks:
   - ukama-net
  depends_on:
   - postgresd-node

 initclient-node:
  image: main-init
  environment:
   - ENV_SYSTEM_ORG=ukama
   - ENV_DNS_REFRESH_TIME_PERIOD=30
   - ENV_SYSTEM_NAME=node
   - ENV_SYSTEM_DNS=api-gateway-node
   - ENV_DNS_SERVER=false
   - ENV_SYSTEM_PORT=8080
   - ENV_SYSTEM_CERT=This-is-a-certificate
   - ENV_INIT_SYSTEM_ADDR=192.168.0.138
   - ENV_INIT_SYSTEM_PORT=8071
   - ENV_INIT_CLIENT_ADDR=initclient-node
   - ENV_INIT_CLIENT_PORT=8080
   - ENV_INIT_CLIENT_TEMP_FILE=/tmp/tmpfile
   - ENV_SYSTEM_DNS_NODE_GW=node-gateway-node
   - ENV_SYSTEM_NODE_GW_PORT=8080
  restart: always
  networks:
   - ukama-net

 configurator:
  build: ./configurator
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@192.168.0.138:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - CONFIGURATOR_SERVICE_HOST=configurator
   - CONFIGURATOR_SERVICE_PORT=9090
   - PUSHGATEWAY=http://192.168.0.138:9091
   - ORGNAME=ukama
   - LATESTCONFIGHASH=${LATESTCONFIGHASH}
   - STOREURL=${STOREURL}
   - STOREUSER=root
   - ACCESSTOKEN=${ACCESSTOKEN}
   - HTTP_INITCLIENT=http://api-gateway-init:8080
   - OPERATION_MANAGERHOST=manager:9090
   - OPERATION_LEASESECS=1800
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-node

networks:
 ukama-net:
  external: true
  name: services_ukama-net

volumes:
 postgress-data:
