version: '3.2'
services:
 postgresd-node:
  image: postgres:13.3
  ports:
   - '5415:5432'
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Pass2020!
  networks:
   - ukama-net
  volumes:
   - postgress-data:/var/lib/postgresql

 api-gateway-registry:
  build:
   dockerfile: ./Dockerfile
   context: ./api-gateway
  restart: always
  ports:
   - '8040:8080'
  networks:
   - ukama-net
  environment:
   - DEBUGMODE=true
   - BYPASS_AUTH_MODE=true
   # - CORS_ALLOWALLORIGINS=true
   # - CORS_ALLOWORIGINS=""
  depends_on:
   - configurator
   - postgresd-node

 configurator:
  build: ./configurator
  ports:
   - '9040:9090'
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGID=018688fa-d861-4e7b-b119-ffc5e1637ba8
   - ORGNAME=ukama-test-org
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-node:9095
   - MEMBER_SERVICE_HOST=configurator
   - MEMBER_SERVICE_PORT=9090
   - OWNERID=018688fa-d861-4e7b-b119-ffc5e1637ba8
   - PUSHGATEWAY=http://${LOCAL_HOST_IP}:9099
   - ORGREGISTRYHOST=http://${LOCAL_HOST_IP}:8060
   - LATESTCONFIGHASH=99c95ddcfeb5e49e87020e7cfd7c9c86abf38b03
   - STOREURL=http://192.168.0.26:8088/ukama/ukama-test-org.git
   - STOREUSER=root
   - ACCESSTOKEN=JxNWc+2iypnqqZytumDBVFY7rzxod4tajONTwdineYI=
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-node

 msgclient-node:
  build: ../services/msgClient
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-node
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - SYSTEM=node
  restart: always
  networks:
   - ukama-net
  depends_on:
   - postgresd-node

networks:
 ukama-net:
  external: true
  name: services_dev-net

volumes:
 postgress-data:
