version: "3.7"

services:
  postgresd:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    networks:
      - rest-service-network
    volumes:
      - postgress-data:/var/lib/postgresql



  rest-service: # Here, this is where you can configure your gateway.
    build: .
    ports: [ "8080:8080" ]
    networks:
      - rest-service-network
    restart: always
    environment:
      - DEBUGMODE=true
      - DB_HOST=postgresd
      - DB_PASSWORD=pass
      - DB_USER=postgres



networks:
  rest-service-network: