packages:
  # include all source files
  - 'src/**'
  # exclude test directories
  - '!**/test/**'
  - '!**/__tests__/**'
  - 'testing/console/**'
  # exclude build and cache directories
  - '!**/node_modules/**'
  - '!**/.next/**'
  - '!**/.temp/**'
