// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	clients "github.com/ukama/ukama/systems/analytics/collector/pkg/clients"
)

// BillingClient is an autogenerated mock type for the BillingClient type
type BillingClient struct {
	mock.Mock
}

// GetAccount provides a mock function with no fields
func (_m *BillingClient) GetAccount() (*clients.BillingAccount, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *clients.BillingAccount
	var r1 error
	if rf, ok := ret.Get(0).(func() (*clients.BillingAccount, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *clients.BillingAccount); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.BillingAccount)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBillingClient creates a new instance of BillingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingClient {
	mock := &BillingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
