// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/collector/pkg/db"
)

// EventRepo is an autogenerated mock type for the EventRepo type
type EventRepo struct {
	mock.Mock
}

// GetRecent provides a mock function with given fields: limit
func (_m *EventRepo) GetRecent(limit int) ([]db.EventLog, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []db.EventLog
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]db.EventLog, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []db.EventLog); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.EventLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogEvent provides a mock function with given fields: log
func (_m *EventRepo) LogEvent(log *db.EventLog) (bool, error) {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for LogEvent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*db.EventLog) (bool, error)); ok {
		return rf(log)
	}
	if rf, ok := ret.Get(0).(func(*db.EventLog) bool); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*db.EventLog) error); ok {
		r1 = rf(log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordError provides a mock function with given fields: e
func (_m *EventRepo) RecordError(e *db.EventError) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for RecordError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.EventError) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventRepo creates a new instance of EventRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepo {
	mock := &EventRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
