openapi: 3.0.1
info:
    title: AUTH System
    description: Auth system provides authentication and authorization features
    version: v0.0.debug
servers:
    - url: AUTH_URL
      description: AUTH API V1
paths:
    /ping:
        get:
            summary: Ping
            description: Service health check
            operationId: func1
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RestPingResponse'
    /v1/auth:
        get:
            tags:
                - Auth System
            summary: Authenticate user
            operationId: authenticate-fm
            parameters:
                - name: org-id
                  in: header
                  schema:
                    type: string
                    example: ORG_ID
                - name: x-session-token
                  in: header
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
    /v1/login:
        post:
            tags:
                - Auth System
            summary: Login user
            operationId: login-fm
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Login-FmInput'
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RestLoginRes'
    /v1/role:
        put:
            tags:
                - Auth System
            summary: Update user role
            operationId: updateRole-fm
            parameters:
                - name: org-id
                  in: header
                  schema:
                    type: string
                    example: '{{ORG_ID}}'
                - name: x-session-token
                  in: header
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRole-FmInput'
            responses:
                "200":
                    description: OK
    /v1/whoami:
        get:
            tags:
                - Auth System
            summary: Get user info
            operationId: getUserInfo-fm
            parameters:
                - name: org-id
                  in: header
                  schema:
                    type: string
                    example: ORG_ID
                - name: x-session-token
                  in: header
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RestGetUserInfo'
components:
    schemas:
        Login-FmInput:
            type: object
            properties:
                email:
                    type: string
                    example: john@example.com
                password:
                    type: string
                    example: Password
        RestGetUserInfo:
            type: object
            properties:
                email:
                    type: string
                    example: john@example.com
                first_visit:
                    type: boolean
                    example: true
                id:
                    type: string
                    example: "1"
                name:
                    type: string
                    example: John Doe
                role:
                    type: string
                    example: admin
        RestLoginRes:
            type: object
            properties:
                token:
                    type: string
                    example: Token
        RestPingResponse:
            type: object
            properties:
                message:
                    type: string
                service:
                    type: string
        UpdateRole-FmInput:
            type: object
            properties:
                role:
                    type: string
                    example: member
tags:
    - name: Auth System
      description: Auth system provides authentication and authorization features
