// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/registry/org/pkg/db"

	uuid "github.com/google/uuid"
)

// OrgRepo is an autogenerated mock type for the OrgRepo type
type OrgRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: org
func (_m *OrgRepo) Add(org *db.Org) error {
	ret := _m.Called(org)

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.Org) error); ok {
		r0 = rf(org)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddMember provides a mock function with given fields: org, user
func (_m *OrgRepo) AddMember(org *db.Org, user *db.User) (*db.OrgUser, error) {
	ret := _m.Called(org, user)

	var r0 *db.OrgUser
	if rf, ok := ret.Get(0).(func(*db.Org, *db.User) *db.OrgUser); ok {
		r0 = rf(org, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.OrgUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*db.Org, *db.User) error); ok {
		r1 = rf(org, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *OrgRepo) Get(id int) (*db.Org, error) {
	ret := _m.Called(id)

	var r0 *db.Org
	if rf, ok := ret.Get(0).(func(int) *db.Org); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Org)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByOwner provides a mock function with given fields: _a0
func (_m *OrgRepo) GetByOwner(_a0 uuid.UUID) ([]db.Org, error) {
	ret := _m.Called(_a0)

	var r0 []db.Org
	if rf, ok := ret.Get(0).(func(uuid.UUID) []db.Org); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Org)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrgRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrgRepo creates a new instance of OrgRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrgRepo(t mockConstructorTestingTNewOrgRepo) *OrgRepo {
	mock := &OrgRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
