// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	pkg "github.com/ukama/ukama/services/cloud/device-feeder/pkg"
)

// QueuePublisher is an autogenerated mock type for the QueuePublisher type
type QueuePublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: msg
func (_m *QueuePublisher) Publish(msg pkg.DevicesUpdateRequest) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(pkg.DevicesUpdateRequest) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
