// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/services/cloud/network/pb/gen"

	testing "testing"
)

// NetworkClient is an autogenerated mock type for the NetworkClient type
type NetworkClient struct {
	mock.Mock
}

// GetNodesList provides a mock function with given fields: orgName
func (_m *NetworkClient) GetNodesList(orgName string) ([]*gen.Node, error) {
	ret := _m.Called(orgName)

	var r0 []*gen.Node
	if rf, ok := ret.Get(0).(func(string) []*gen.Node); ok {
		r0 = rf(orgName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gen.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orgName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNetworkClient creates a new instance of NetworkClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewNetworkClient(t testing.TB) *NetworkClient {
	mock := &NetworkClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
