// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/services/cloud/registry/pb/gen"
)

// RegistryClient is an autogenerated mock type for the RegistryClient type
type RegistryClient struct {
	mock.Mock
}

// GetNodesList provides a mock function with given fields: orgName
func (_m *RegistryClient) GetNodesList(orgName string) ([]*gen.Node, error) {
	ret := _m.Called(orgName)

	var r0 []*gen.Node
	if rf, ok := ret.Get(0).(func(string) []*gen.Node); ok {
		r0 = rf(orgName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gen.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orgName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
