// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/network/pkg/db"
)

// AlarmRepo is an autogenerated mock type for the AlarmRepo type
type AlarmRepo struct {
	mock.Mock
}

// Counts provides a mock function with given fields: networkId, siteId
func (_m *AlarmRepo) Counts(networkId string, siteId string) (*db.AlarmCounts, error) {
	ret := _m.Called(networkId, siteId)

	if len(ret) == 0 {
		panic("no return value specified for Counts")
	}

	var r0 *db.AlarmCounts
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*db.AlarmCounts, error)); ok {
		return rf(networkId, siteId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *db.AlarmCounts); ok {
		r0 = rf(networkId, siteId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.AlarmCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(networkId, siteId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ForResource provides a mock function with given fields: resourceType, resourceId, limit
func (_m *AlarmRepo) ForResource(resourceType string, resourceId string, limit int) ([]db.AlarmEvent, error) {
	ret := _m.Called(resourceType, resourceId, limit)

	if len(ret) == 0 {
		panic("no return value specified for ForResource")
	}

	var r0 []db.AlarmEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) ([]db.AlarmEvent, error)); ok {
		return rf(resourceType, resourceId, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) []db.AlarmEvent); ok {
		r0 = rf(resourceType, resourceId, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.AlarmEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(resourceType, resourceId, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: filter
func (_m *AlarmRepo) List(filter db.AlarmFilter) ([]db.AlarmEvent, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.AlarmEvent
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(db.AlarmFilter) ([]db.AlarmEvent, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(db.AlarmFilter) []db.AlarmEvent); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.AlarmEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(db.AlarmFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(db.AlarmFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// OpenImpact provides a mock function with given fields: networkId
func (_m *AlarmRepo) OpenImpact(networkId string) (int64, float64, error) {
	ret := _m.Called(networkId)

	if len(ret) == 0 {
		panic("no return value specified for OpenImpact")
	}

	var r0 int64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (int64, float64, error)); ok {
		return rf(networkId)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(networkId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) float64); ok {
		r1 = rf(networkId)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(networkId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAlarmRepo creates a new instance of AlarmRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlarmRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlarmRepo {
	mock := &AlarmRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
