// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/network/pkg/db"

	time "time"
)

// EventRepo is an autogenerated mock type for the EventRepo type
type EventRepo struct {
	mock.Mock
}

// Recent provides a mock function with given fields: networkId, siteId, nodeId, from, to, page, pageSize
func (_m *EventRepo) Recent(networkId string, siteId string, nodeId string, from time.Time, to time.Time, page uint32, pageSize uint32) ([]db.EventLog, int64, error) {
	ret := _m.Called(networkId, siteId, nodeId, from, to, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for Recent")
	}

	var r0 []db.EventLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, time.Time, time.Time, uint32, uint32) ([]db.EventLog, int64, error)); ok {
		return rf(networkId, siteId, nodeId, from, to, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, time.Time, time.Time, uint32, uint32) []db.EventLog); ok {
		r0 = rf(networkId, siteId, nodeId, from, to, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.EventLog)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, time.Time, time.Time, uint32, uint32) int64); ok {
		r1 = rf(networkId, siteId, nodeId, from, to, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, time.Time, time.Time, uint32, uint32) error); ok {
		r2 = rf(networkId, siteId, nodeId, from, to, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewEventRepo creates a new instance of EventRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepo {
	mock := &EventRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
