// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/network/pkg/db"

	time "time"
)

// HealthRepo is an autogenerated mock type for the HealthRepo type
type HealthRepo struct {
	mock.Mock
}

// NetworkHealthLatest provides a mock function with given fields: networkId
func (_m *HealthRepo) NetworkHealthLatest(networkId string) (*db.NetworkHealthRollupHourly, error) {
	ret := _m.Called(networkId)

	if len(ret) == 0 {
		panic("no return value specified for NetworkHealthLatest")
	}

	var r0 *db.NetworkHealthRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NetworkHealthRollupHourly, error)); ok {
		return rf(networkId)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NetworkHealthRollupHourly); ok {
		r0 = rf(networkId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NetworkHealthRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(networkId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkHealthSeries provides a mock function with given fields: networkId, from, to
func (_m *HealthRepo) NetworkHealthSeries(networkId string, from time.Time, to time.Time) ([]db.NetworkHealthRollupHourly, error) {
	ret := _m.Called(networkId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for NetworkHealthSeries")
	}

	var r0 []db.NetworkHealthRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) ([]db.NetworkHealthRollupHourly, error)); ok {
		return rf(networkId, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) []db.NetworkHealthRollupHourly); ok {
		r0 = rf(networkId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NetworkHealthRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(networkId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthRepo creates a new instance of HealthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthRepo {
	mock := &HealthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
