// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/network/pkg/db"

	time "time"
)

// MetricRepo is an autogenerated mock type for the MetricRepo type
type MetricRepo struct {
	mock.Mock
}

// BackhaulRollups provides a mock function with given fields: siteId, from, to
func (_m *MetricRepo) BackhaulRollups(siteId string, from time.Time, to time.Time) ([]db.BackhaulRollupHourly, error) {
	ret := _m.Called(siteId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for BackhaulRollups")
	}

	var r0 []db.BackhaulRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) ([]db.BackhaulRollupHourly, error)); ok {
		return rf(siteId, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) []db.BackhaulRollupHourly); ok {
		r0 = rf(siteId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.BackhaulRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(siteId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LatestBackhaulRollup provides a mock function with given fields: siteId
func (_m *MetricRepo) LatestBackhaulRollup(siteId string) (*db.BackhaulRollupHourly, error) {
	ret := _m.Called(siteId)

	if len(ret) == 0 {
		panic("no return value specified for LatestBackhaulRollup")
	}

	var r0 *db.BackhaulRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.BackhaulRollupHourly, error)); ok {
		return rf(siteId)
	}
	if rf, ok := ret.Get(0).(func(string) *db.BackhaulRollupHourly); ok {
		r0 = rf(siteId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BackhaulRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(siteId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LatestPowerRollup provides a mock function with given fields: siteId
func (_m *MetricRepo) LatestPowerRollup(siteId string) (*db.PowerRollupHourly, error) {
	ret := _m.Called(siteId)

	if len(ret) == 0 {
		panic("no return value specified for LatestPowerRollup")
	}

	var r0 *db.PowerRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.PowerRollupHourly, error)); ok {
		return rf(siteId)
	}
	if rf, ok := ret.Get(0).(func(string) *db.PowerRollupHourly); ok {
		r0 = rf(siteId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.PowerRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(siteId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LatestRadioRollup provides a mock function with given fields: nodeId
func (_m *MetricRepo) LatestRadioRollup(nodeId string) (*db.RadioRollupHourly, error) {
	ret := _m.Called(nodeId)

	if len(ret) == 0 {
		panic("no return value specified for LatestRadioRollup")
	}

	var r0 *db.RadioRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.RadioRollupHourly, error)); ok {
		return rf(nodeId)
	}
	if rf, ok := ret.Get(0).(func(string) *db.RadioRollupHourly); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.RadioRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LatestSamples provides a mock function with given fields: resourceId, limit
func (_m *MetricRepo) LatestSamples(resourceId string, limit int) ([]db.MetricSample, error) {
	ret := _m.Called(resourceId, limit)

	if len(ret) == 0 {
		panic("no return value specified for LatestSamples")
	}

	var r0 []db.MetricSample
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]db.MetricSample, error)); ok {
		return rf(resourceId, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []db.MetricSample); ok {
		r0 = rf(resourceId, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.MetricSample)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(resourceId, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricNames provides a mock function with given fields: resourceId
func (_m *MetricRepo) MetricNames(resourceId string) ([]db.MetricName, error) {
	ret := _m.Called(resourceId)

	if len(ret) == 0 {
		panic("no return value specified for MetricNames")
	}

	var r0 []db.MetricName
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]db.MetricName, error)); ok {
		return rf(resourceId)
	}
	if rf, ok := ret.Get(0).(func(string) []db.MetricName); ok {
		r0 = rf(resourceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.MetricName)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(resourceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PowerRollups provides a mock function with given fields: siteId, from, to
func (_m *MetricRepo) PowerRollups(siteId string, from time.Time, to time.Time) ([]db.PowerRollupHourly, error) {
	ret := _m.Called(siteId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for PowerRollups")
	}

	var r0 []db.PowerRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) ([]db.PowerRollupHourly, error)); ok {
		return rf(siteId, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) []db.PowerRollupHourly); ok {
		r0 = rf(siteId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.PowerRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(siteId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadioRollupSums provides a mock function with given fields: networkId, at
func (_m *MetricRepo) RadioRollupSums(networkId string, at time.Time) (int64, int64, error) {
	ret := _m.Called(networkId, at)

	if len(ret) == 0 {
		panic("no return value specified for RadioRollupSums")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, time.Time) (int64, int64, error)); ok {
		return rf(networkId, at)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) int64); ok {
		r0 = rf(networkId, at)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) int64); ok {
		r1 = rf(networkId, at)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, time.Time) error); ok {
		r2 = rf(networkId, at)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RadioRollups provides a mock function with given fields: nodeId, from, to
func (_m *MetricRepo) RadioRollups(nodeId string, from time.Time, to time.Time) ([]db.RadioRollupHourly, error) {
	ret := _m.Called(nodeId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for RadioRollups")
	}

	var r0 []db.RadioRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) ([]db.RadioRollupHourly, error)); ok {
		return rf(nodeId, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) []db.RadioRollupHourly); ok {
		r0 = rf(nodeId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.RadioRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(nodeId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollups provides a mock function with given fields: metric, resourceType, resourceId, from, to
func (_m *MetricRepo) Rollups(metric string, resourceType string, resourceId string, from time.Time, to time.Time) ([]db.MetricRollupHourly, error) {
	ret := _m.Called(metric, resourceType, resourceId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for Rollups")
	}

	var r0 []db.MetricRollupHourly
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, time.Time, time.Time) ([]db.MetricRollupHourly, error)); ok {
		return rf(metric, resourceType, resourceId, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, time.Time, time.Time) []db.MetricRollupHourly); ok {
		r0 = rf(metric, resourceType, resourceId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.MetricRollupHourly)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, time.Time, time.Time) error); ok {
		r1 = rf(metric, resourceType, resourceId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMetricRepo creates a new instance of MetricRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricRepo {
	mock := &MetricRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
