// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/analytics/network/pkg/db"

	time "time"
)

// NodeRepo is an autogenerated mock type for the NodeRepo type
type NodeRepo struct {
	mock.Mock
}

// ConfiguringDuration provides a mock function with given fields: nodeId
func (_m *NodeRepo) ConfiguringDuration(nodeId string) (float64, error) {
	ret := _m.Called(nodeId)

	if len(ret) == 0 {
		panic("no return value specified for ConfiguringDuration")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(nodeId)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(nodeId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: nodeId
func (_m *NodeRepo) Get(nodeId string) (*db.NodeSnapshot, error) {
	ret := _m.Called(nodeId)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *db.NodeSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NodeSnapshot, error)); ok {
		return rf(nodeId)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NodeSnapshot); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NodeSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: networkId, siteId, status, page, pageSize
func (_m *NodeRepo) List(networkId string, siteId string, status string, page uint32, pageSize uint32) ([]db.NodeSnapshot, int64, error) {
	ret := _m.Called(networkId, siteId, status, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.NodeSnapshot
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, uint32, uint32) ([]db.NodeSnapshot, int64, error)); ok {
		return rf(networkId, siteId, status, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, uint32, uint32) []db.NodeSnapshot); ok {
		r0 = rf(networkId, siteId, status, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NodeSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, uint32, uint32) int64); ok {
		r1 = rf(networkId, siteId, status, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, uint32, uint32) error); ok {
		r2 = rf(networkId, siteId, status, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListAll provides a mock function with given fields: networkId
func (_m *NodeRepo) ListAll(networkId string) ([]db.NodeSnapshot, error) {
	ret := _m.Called(networkId)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []db.NodeSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]db.NodeSnapshot, error)); ok {
		return rf(networkId)
	}
	if rf, ok := ret.Get(0).(func(string) []db.NodeSnapshot); ok {
		r0 = rf(networkId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NodeSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(networkId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PoolCounts provides a mock function with given fields: networkId
func (_m *NodeRepo) PoolCounts(networkId string) (*db.NodePoolCounts, error) {
	ret := _m.Called(networkId)

	if len(ret) == 0 {
		panic("no return value specified for PoolCounts")
	}

	var r0 *db.NodePoolCounts
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NodePoolCounts, error)); ok {
		return rf(networkId)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NodePoolCounts); ok {
		r0 = rf(networkId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NodePoolCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(networkId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: query, networkId, limit
func (_m *NodeRepo) Search(query string, networkId string, limit int) ([]db.NodeSnapshot, error) {
	ret := _m.Called(query, networkId, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []db.NodeSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) ([]db.NodeSnapshot, error)); ok {
		return rf(query, networkId, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) []db.NodeSnapshot); ok {
		r0 = rf(query, networkId, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NodeSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(query, networkId, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatusCounts provides a mock function with given fields: networkId, siteId
func (_m *NodeRepo) StatusCounts(networkId string, siteId string) (*db.NodeStatusCounts, error) {
	ret := _m.Called(networkId, siteId)

	if len(ret) == 0 {
		panic("no return value specified for StatusCounts")
	}

	var r0 *db.NodeStatusCounts
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*db.NodeStatusCounts, error)); ok {
		return rf(networkId, siteId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *db.NodeStatusCounts); ok {
		r0 = rf(networkId, siteId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NodeStatusCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(networkId, siteId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UptimeBetween provides a mock function with given fields: nodeId, from, to
func (_m *NodeRepo) UptimeBetween(nodeId string, from time.Time, to time.Time) (float64, error) {
	ret := _m.Called(nodeId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for UptimeBetween")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) (float64, error)); ok {
		return rf(nodeId, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) float64); ok {
		r0 = rf(nodeId, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(nodeId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNodeRepo creates a new instance of NodeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeRepo {
	mock := &NodeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
