// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/ukama/ukama/systems/api/api-gateway/pkg/client"
)

// PackageClient is an autogenerated mock type for the PackageClient type
type PackageClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: Id
func (_m *PackageClient) Get(Id string) (*client.PackageInfo, error) {
	ret := _m.Called(Id)

	var r0 *client.PackageInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*client.PackageInfo, error)); ok {
		return rf(Id)
	}
	if rf, ok := ret.Get(0).(func(string) *client.PackageInfo); ok {
		r0 = rf(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PackageInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPackageClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewPackageClient creates a new instance of PackageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPackageClient(t mockConstructorTestingTNewPackageClient) *PackageClient {
	mock := &PackageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
