// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "github.com/ukama/ukama/systems/api/api-gateway/pkg/client/rest"
)

// SimClient is an autogenerated mock type for the SimClient type
type SimClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: req
func (_m *SimClient) Add(req rest.AddSimRequest) (*rest.SimInfo, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *rest.SimInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(rest.AddSimRequest) (*rest.SimInfo, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(rest.AddSimRequest) *rest.SimInfo); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.SimInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(rest.AddSimRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: Id
func (_m *SimClient) Get(Id string) (*rest.SimInfo, error) {
	ret := _m.Called(Id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rest.SimInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*rest.SimInfo, error)); ok {
		return rf(Id)
	}
	if rf, ok := ret.Get(0).(func(string) *rest.SimInfo); ok {
		r0 = rf(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.SimInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSimClient creates a new instance of SimClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimClient {
	mock := &SimClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
