// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "github.com/ukama/ukama/systems/api/api-gateway/pkg/client/rest"
)

// SubscriberClient is an autogenerated mock type for the SubscriberClient type
type SubscriberClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: req
func (_m *SubscriberClient) Add(req rest.AddSubscriberRequest) (*rest.SubscriberInfo, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *rest.SubscriberInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(rest.AddSubscriberRequest) (*rest.SubscriberInfo, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(rest.AddSubscriberRequest) *rest.SubscriberInfo); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.SubscriberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(rest.AddSubscriberRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: Id
func (_m *SubscriberClient) Get(Id string) (*rest.SubscriberInfo, error) {
	ret := _m.Called(Id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rest.SubscriberInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*rest.SubscriberInfo, error)); ok {
		return rf(Id)
	}
	if rf, ok := ret.Get(0).(func(string) *rest.SubscriberInfo); ok {
		r0 = rf(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.SubscriberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriberClient creates a new instance of SubscriberClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriberClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriberClient {
	mock := &SubscriberClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
