// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/node/controller/pb/gen"
)

// controller is an autogenerated mock type for the controller type
type controller struct {
	mock.Mock
}

// PingNode provides a mock function with given fields: _a0
func (_m *controller) PingNode(_a0 *gen.PingNodeRequest) (*gen.PingNodeResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for PingNode")
	}

	var r0 *gen.PingNodeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.PingNodeRequest) (*gen.PingNodeResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*gen.PingNodeRequest) *gen.PingNodeResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.PingNodeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.PingNodeRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestartNode provides a mock function with given fields: nodeId
func (_m *controller) RestartNode(nodeId string) (*gen.RestartNodeResponse, error) {
	ret := _m.Called(nodeId)

	if len(ret) == 0 {
		panic("no return value specified for RestartNode")
	}

	var r0 *gen.RestartNodeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*gen.RestartNodeResponse, error)); ok {
		return rf(nodeId)
	}
	if rf, ok := ret.Get(0).(func(string) *gen.RestartNodeResponse); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.RestartNodeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestartNodes provides a mock function with given fields: networkId, nodeIds
func (_m *controller) RestartNodes(networkId string, nodeIds []string) (*gen.RestartNodesResponse, error) {
	ret := _m.Called(networkId, nodeIds)

	if len(ret) == 0 {
		panic("no return value specified for RestartNodes")
	}

	var r0 *gen.RestartNodesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (*gen.RestartNodesResponse, error)); ok {
		return rf(networkId, nodeIds)
	}
	if rf, ok := ret.Get(0).(func(string, []string) *gen.RestartNodesResponse); ok {
		r0 = rf(networkId, nodeIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.RestartNodesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(networkId, nodeIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestartSite provides a mock function with given fields: siteName, networkId
func (_m *controller) RestartSite(siteName string, networkId string) (*gen.RestartSiteResponse, error) {
	ret := _m.Called(siteName, networkId)

	if len(ret) == 0 {
		panic("no return value specified for RestartSite")
	}

	var r0 *gen.RestartSiteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*gen.RestartSiteResponse, error)); ok {
		return rf(siteName, networkId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *gen.RestartSiteResponse); ok {
		r0 = rf(siteName, networkId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.RestartSiteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(siteName, networkId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleInternetSwitch provides a mock function with given fields: status, port, siteId
func (_m *controller) ToggleInternetSwitch(status bool, port int32, siteId string) (*gen.ToggleInternetSwitchResponse, error) {
	ret := _m.Called(status, port, siteId)

	if len(ret) == 0 {
		panic("no return value specified for ToggleInternetSwitch")
	}

	var r0 *gen.ToggleInternetSwitchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(bool, int32, string) (*gen.ToggleInternetSwitchResponse, error)); ok {
		return rf(status, port, siteId)
	}
	if rf, ok := ret.Get(0).(func(bool, int32, string) *gen.ToggleInternetSwitchResponse); ok {
		r0 = rf(status, port, siteId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ToggleInternetSwitchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(bool, int32, string) error); ok {
		r1 = rf(status, port, siteId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleRf provides a mock function with given fields: nodeId, status
func (_m *controller) ToggleRf(nodeId string, status bool) (*gen.ToggleRfSwitchResponse, error) {
	ret := _m.Called(nodeId, status)

	if len(ret) == 0 {
		panic("no return value specified for ToggleRf")
	}

	var r0 *gen.ToggleRfSwitchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (*gen.ToggleRfSwitchResponse, error)); ok {
		return rf(nodeId, status)
	}
	if rf, ok := ret.Get(0).(func(string, bool) *gen.ToggleRfSwitchResponse); ok {
		r0 = rf(nodeId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ToggleRfSwitchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(nodeId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newController creates a new instance of controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newController(t interface {
	mock.TestingT
	Cleanup(func())
}) *controller {
	mock := &controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
