[LWM2M.Object]
Name = "Digital Input"
Description1 = "Generic digital input for non-specific sensors"
ObjectID = 3200
ObjectURN = "urn:oma:lwm2m:ext:3200:1.1"
LWM2MVersion = 1
ObjectVersion = "1.1"
MultipleInstances = "Multiple"
Mandatory = "Optional"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "Digital Input State"
Operations = "R"
ResourceID = 5500
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Boolean"
RangeEnumeration = ""
Units = ""
Description = "The current state of a digital input."

[[LWM2M.Object.Resources.Item]]
Name = "Digital Input Counter"
Operations = "R"
ResourceID = 5501
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "The cumulative value of active state detected."

[[LWM2M.Object.Resources.Item]]
Name = "Digital Input Polarity"
ResourceID = 5502
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Boolean"
RangeEnumeration = ""
Units = ""
Description = "The polarity of the digital input as a Boolean (False = Normal, True = Reversed)."

[[LWM2M.Object.Resources.Item]]
Name = "Digital Input Debounce"
ResourceID = 5503
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = ""
Units = "ms"
Description = "The debounce period in ms."

[[LWM2M.Object.Resources.Item]]
Name = "Digital Input Edge Selection"
ResourceID = 5504
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = "1..3"
Units = ""
Description = "The edge selection as an integer (1 = Falling edge, 2 = Rising edge, 3 = Both Rising and Falling edge)."

[[LWM2M.Object.Resources.Item]]
Name = "Digital Input Counter Reset"
ResourceID = 5505
Operations = "E"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = ""
RangeEnumeration = ""
Units = ""
Description = "Reset the Counter value."

[[LWM2M.Object.Resources.Item]]
Name = "Application Type"
ResourceID = 5750
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "The application type of the sensor or actuator as a string depending on the use case."

[[LWM2M.Object.Resources.Item]]
Name = "Sensor Type"
ResourceID = 5751
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "The type of the sensor (for instance PIR type)."

[[LWM2M.Object.Resources.Item]]
Name = "Timestamp"
ResourceID = 5518
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Time"
RangeEnumeration = ""
Units = ""
Description = "The timestamp of when the measurement was performed."

[[LWM2M.Object.Resources.Item]]
Name = "Fractional Timestamp"
ResourceID = 6050
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = "0..1"
Units = "s"
Description = "Fractional part of the timestamp when sub-second precision is used (e.g., 0.23 for 230 ms)."
