[LWM2M.Object]
Name = "Analog Output"
Description1 = "This IPSO object is a generic object that can be used with any kind of analog output interface."
ObjectID = 3203
ObjectURN = "urn:oma:lwm2m:ext:3203:1.1"
LWM2MVersion = 1
ObjectVersion = "1.1"
MultipleInstances = "Multiple"
Mandatory = "Optional"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "Analog Output Current Value"
ResourceID = 5650
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Float"
RangeEnumeration = "0..1"
Units = ""
Description = "The current value of the analog output."

[[LWM2M.Object.Resources.Item]]
Name = "Application Type"
ResourceID = 5750
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "The application type of the sensor or actuator as a string depending on the use case."

[[LWM2M.Object.Resources.Item]]
Name = "Min Range Value"
ResourceID = 5603
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The minimum value that can be measured by the sensor."

[[LWM2M.Object.Resources.Item]]
Name = "Max Range Value"
ResourceID = 5604
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The maximum value that can be measured by the sensor."

[[LWM2M.Object.Resources.Item]]
Name = "Timestamp"
ResourceID = 5518
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Time"
RangeEnumeration = ""
Units = ""
Description = "The timestamp of when the measurement was performed."

[[LWM2M.Object.Resources.Item]]
Name = "Fractional Timestamp"
ResourceID = 6050
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = "0..1"
Units = "s"
Description = "Fractional part of the timestamp when sub-second precision is used (e.g., 0.23 for 230 ms)."
