[LWM2M.Object]
Name = "Light Control"
Description1 = "This Object is used to control a light source, such as a LED or other light.  It allows a light to be turned on or off and its dimmer setting to be control as a % between 0 and 100. An optional colour setting enables a string to be used to indicate the desired colour."
ObjectID = 3311
ObjectURN = "urn:oma:lwm2m:ext:3311"
LWM2MVersion = 1
ObjectVersion = "1"
MultipleInstances = "Multiple"
Mandatory = "Optional"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "On/Off"
ResourceID = 5850
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Boolean"
RangeEnumeration = ""
Units = ""
Description = "On/off control. Boolean value where True is On and False is Off."

[[LWM2M.Object.Resources.Item]]
Name = "Dimmer"
ResourceID = 5851
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = "0..100"
Units = "/100"
Description = "This resource represents a dimmer setting, which has an Integer value between 0 and 100 as a percentage."

[[LWM2M.Object.Resources.Item]]
Name = "On time"
ResourceID = 5852
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = ""
Units = "s"
Description = "The time in seconds that the device has been on. Writing a value of 0 resets the counter."

[[LWM2M.Object.Resources.Item]]
Name = "Cummulative active power"
ResourceID = 5805
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = "Wh"
Description = "The cumulative active power since the last cumulative energy reset or device start."

[[LWM2M.Object.Resources.Item]]
Name = "Power factor"
ResourceID = 5820
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "If applicable, the power factor of the current consumption."

[[LWM2M.Object.Resources.Item]]
Name = "Colour"
ResourceID = 5606
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "A string representing a value in some color space."

[[LWM2M.Object.Resources.Item]]
Name = "Sensor Units"
ResourceID = 5701
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Measurement Units Definition."

[[LWM2M.Object.Resources.Item]]
Name = "Application Type"
ResourceID = 5750
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "The application type of the sensor or actuator as a string depending on the use case."
