[LWM2M.Object]
Name = "Voltage"
Description1 = "This IPSO object should be used with voltmeter sensor to report measured voltage between two points.  It also provides resources for minimum and maximum measured values, as well as the minimum and maximum range that can be measured by the sensor. An example measurement unit is volts."
ObjectID = 3316
ObjectURN = "urn:oma:lwm2m:ext:3316:1.1"
LWM2MVersion = 1
ObjectVersion = "1.1"
MultipleInstances = "Multiple"
Mandatory = "Optional"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "Sensor Value"
ResourceID = 5700
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "Last or Current Measured Value from the Sensor."

[[LWM2M.Object.Resources.Item]]
Name = "Sensor Units"
ResourceID = 5701
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Measurement Units Definition."

[[LWM2M.Object.Resources.Item]]
Name = "Min Measured Value"
ResourceID = 5601
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The minimum value measured by the sensor since power ON or reset."

[[LWM2M.Object.Resources.Item]]
Name = "Max Measured Value"
ResourceID = 5602
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The maximum value measured by the sensor since power ON or reset."

[[LWM2M.Object.Resources.Item]]
Name = "Min Range Value"
ResourceID = 5603
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The minimum value that can be measured by the sensor."

[[LWM2M.Object.Resources.Item]]
Name = "Max Range Value"
ResourceID = 5604
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The maximum value that can be measured by the sensor."

[[LWM2M.Object.Resources.Item]]
Name = "Reset Min and Max Measured Values"
ResourceID = 5605
Operations = "E"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = ""
RangeEnumeration = ""
Units = ""
Description = "Reset the Min and Max Measured Values to Current Value."

[[LWM2M.Object.Resources.Item]]
Name = "Current Calibration"
ResourceID = 5821
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "Read or Write the current calibration coefficient."

[[LWM2M.Object.Resources.Item]]
Name = "Application Type"
ResourceID = 5750
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "The application type of the sensor or actuator as a string depending on the use case."

[[LWM2M.Object.Resources.Item]]
Name = "Timestamp"
ResourceID = 5518
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Time"
RangeEnumeration = ""
Units = ""
Description = "The timestamp of when the measurement was performed."

[[LWM2M.Object.Resources.Item]]
Name = "Fractional Timestamp"
ResourceID = 6050
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = "0..1"
Units = "s"
Description = "Fractional part of the timestamp when sub-second precision is used (e.g., 0.23 for 230 ms)."

[[LWM2M.Object.Resources.Item]]
Name = "Measurement Quality Indicator"
ResourceID = 6042
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = "0..23"
Units = ""
Description = "Measurement quality indicator reported by a smart sensor. 0: UNCHECKED No quality checks were done because they do not exist or can not be applied. 1: REJECTED WITH CERTAINTY The measured value is invalid. 2: REJECTED WITH PROBABILITY The measured value is likely invalid. 3: ACCEPTED BUT SUSPICIOUS The measured value is likely OK. 4: ACCEPTED The measured value is OK. 5-15: Reserved for future extensions. 16-23: Vendor specific measurement quality."

[[LWM2M.Object.Resources.Item]]
Name = "Measurement Quality Level"
ResourceID = 6049
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = "0..100"
Units = ""
Description = "Measurement quality level reported by a smart sensor. Quality level 100 means that the measurement has fully passed quality check algorithms. Smaller quality levels mean that quality has decreased and the measurement has only partially passed quality check algorithms. The smaller the quality level, the more caution should be used by the application when using the measurement. When the quality level is 0 it means that the measurement should certainly be rejected."
