[LWM2M.Object]
Name = "Module"
Description1 = "This IPSO object should be used to report module details."
ObjectID = 34568
ObjectURN = "urn:oma:lwm2m:x:34568"
LWM2MVersion = 1
ObjectVersion = "1"
MultipleInstances = "Multiple"
Mandatory = "Mandatory"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "UUID"
ResourceID = 0
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Serial ID of the module."

[[LWM2M.Object.Resources.Item]]
Name = "Name"
ResourceID = 1
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Name of the module."

[[LWM2M.Object.Resources.Item]]
Name = "Class"
ResourceID = 2
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "Class of the module."

[[LWM2M.Object.Resources.Item]]
Name = "Part Number"
ResourceID = 3
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "HW Part number."

[[LWM2M.Object.Resources.Item]]
Name = "Manufacturer Name"
ResourceID = 4
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Manufacturer of the module."

[[LWM2M.Object.Resources.Item]]
Name = "Manufacturing Date"
ResourceID = 5
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Manufacturing Date of the module."

[[LWM2M.Object.Resources.Item]]
Name = "MAC"
ResourceID = 6
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "MAC Address for module"

[[LWM2M.Object.Resources.Item]]
Name = "Software Version"
ResourceID = 7
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Software Version of the Module."

[[LWM2M.Object.Resources.Item]]
Name = "Production Software Version"
ResourceID = 8
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Production Software Version agaist which Module was tested."

[[LWM2M.Object.Resources.Item]]
Name = "HW Version"
ResourceID = 9
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "HW Version of the Module."

[[LWM2M.Object.Resources.Item]]
Name = "Sensor Count"
ResourceID = 10
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "Sensor Count on the module."
