[LWM2M.Object]
Name = "Attenuation"
Description1 = "This IPSO object should be used to report and control attenuation."
ObjectID = 34569
ObjectURN = "urn:oma:lwm2m:x:34569"
LWM2MVersion = 1
ObjectVersion = "1"
MultipleInstances = "Multiple"
Mandatory = "Optional"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "Attenuation Value"
ResourceID = 0
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "Current value set for Attenuations."

[[LWM2M.Object.Resources.Item]]
Name = "Min Range"
ResourceID = 1
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "Minimum Value that can be set"

[[LWM2M.Object.Resources.Item]]
Name = "Max Range"
ResourceID = 2
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "Maxmimum Value that can be set"

[[LWM2M.Object.Resources.Item]]
Name = "Latch Enable"
ResourceID = 3
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Boolean"
RangeEnumeration = ""
Units = ""
Description = "Enables or diables attenuation setting"

[[LWM2M.Object.Resources.Item]]
Name = "Sensor Units"
ResourceID = 5701
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Measurement Units Definition."

[[LWM2M.Object.Resources.Item]]
Name = "Application Type"
ResourceID = 5750
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "The application type of the sensor or actuator as a string depending on the use case."
