// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NodeCommandAdapter is an autogenerated mock type for the NodeCommandAdapter type
type NodeCommandAdapter struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, nodeID, method, path, body
func (_m *NodeCommandAdapter) Send(ctx context.Context, nodeID string, method string, path string, body []byte) error {
	ret := _m.Called(ctx, nodeID, method, path, body)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) error); ok {
		r0 = rf(ctx, nodeID, method, path, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNodeCommandAdapter creates a new instance of NodeCommandAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeCommandAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeCommandAdapter {
	mock := &NodeCommandAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
