// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/node/site-controller/pkg/db"
)

// PortMapRepo is an autogenerated mock type for the PortMapRepo type
type PortMapRepo struct {
	mock.Mock
}

// GetBySite provides a mock function with given fields: siteID
func (_m *PortMapRepo) GetBySite(siteID string) ([]db.SitePortMap, error) {
	ret := _m.Called(siteID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySite")
	}

	var r0 []db.SitePortMap
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]db.SitePortMap, error)); ok {
		return rf(siteID)
	}
	if rf, ok := ret.Get(0).(func(string) []db.SitePortMap); ok {
		r0 = rf(siteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SitePortMap)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(siteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: siteID, cnodeID, ports
func (_m *PortMapRepo) Upsert(siteID string, cnodeID string, ports []db.SitePortMap) error {
	ret := _m.Called(siteID, cnodeID, ports)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []db.SitePortMap) error); ok {
		r0 = rf(siteID, cnodeID, ports)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPortMapRepo creates a new instance of PortMapRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortMapRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortMapRepo {
	mock := &PortMapRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
