// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/node/site-controller/pkg/db"
)

// SiteRepo is an autogenerated mock type for the SiteRepo type
type SiteRepo struct {
	mock.Mock
}

// Ensure provides a mock function with given fields: siteID
func (_m *SiteRepo) Ensure(siteID string) error {
	ret := _m.Called(siteID)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(siteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: siteID
func (_m *SiteRepo) Get(siteID string) (*db.Site, error) {
	ret := _m.Called(siteID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *db.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.Site, error)); ok {
		return rf(siteID)
	}
	if rf, ok := ret.Get(0).(func(string) *db.Site); ok {
		r0 = rf(siteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(siteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *SiteRepo) List() ([]db.Site, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.Site
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]db.Site, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []db.Site); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Site)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSiteRepo creates a new instance of SiteRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSiteRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SiteRepo {
	mock := &SiteRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
