// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/node/site-controller/pkg/db"
)

// StateRepo is an autogenerated mock type for the StateRepo type
type StateRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields: siteID
func (_m *StateRepo) Get(siteID string) (*db.SiteState, error) {
	ret := _m.Called(siteID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *db.SiteState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.SiteState, error)); ok {
		return rf(siteID)
	}
	if rf, ok := ret.Get(0).(func(string) *db.SiteState); ok {
		r0 = rf(siteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SiteState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(siteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: patch
func (_m *StateRepo) Upsert(patch *db.SiteState) error {
	ret := _m.Called(patch)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.SiteState) error); ok {
		r0 = rf(patch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStateRepo creates a new instance of StateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateRepo {
	mock := &StateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
