// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: factory.proto

package spec

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EvtUpdateVirtnode) Validate() error {
	return nil
}
