// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	factory "github.com/ukama/ukama/systems/common/rest/client/factory"
)

// NodeFactoryClient is an autogenerated mock type for the NodeFactoryClient type
type NodeFactoryClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: Id
func (_m *NodeFactoryClient) Get(Id string) (*factory.NodeFactoryInfo, error) {
	ret := _m.Called(Id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *factory.NodeFactoryInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*factory.NodeFactoryInfo, error)); ok {
		return rf(Id)
	}
	if rf, ok := ret.Get(0).(func(string) *factory.NodeFactoryInfo); ok {
		r0 = rf(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*factory.NodeFactoryInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNodeFactoryClient creates a new instance of NodeFactoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeFactoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeFactoryClient {
	mock := &NodeFactoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
