services:
 dummy-node:
  build: .
  ports:
   - 8083:8080
   - 8085:8085
  networks:
   ukama-net:
    ipv4_address: 10.1.0.90
  environment:
   - NODE_ID=${NODE_ID}
   - MY_POD_IP=10.1.0.90

networks:
 ukama-net:
  external: true
  name: services_ukama-net
