services:
 postgresd-dummy-node:
  image: postgres:13.3
  ports:
   - 5421:5432
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Pass2020!
  networks:
   - ukama-net

 dnode:
  build: ./dnode
  ports:
   - 9061:9090
  environment:
   - DEBUGMODE=true
   - DB_USER=postgres
   - DB_PASSWORD=Pass2020!
   - DB_HOST=postgresd-dummy-node
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-dummy-node:9095
   - DNODE_SERVICE_HOST=dnode
   - DNODE_SERVICE_PORT=9090
   - ORGID=${ORGID}
   - ORGNAME=${ORGNAME}
  restart: always
  networks:
   - ukama-net
  depends_on:
   - msgclient-dummy-node

 dmetrics:
  build: ./dmetrics
  ports:
   - 8085:8085
  networks:
   ukama-net:
    ipv4_address: 10.1.0.90
  environment:
   - NODE_ID=${NODE_ID}
   - MY_POD_IP=10.1.0.90

 api-gateway:
  build: ./api-gateway
  ports:
   - 8083:8080
  networks:
   - ukama-net
  environment:
   - DEBUGMODE=true
   - BYPASS_AUTH_MODE=true

 msgclient-dummy-node:
  build: ../../../systems/services/msgClient
  environment:
   - DEBUGMODE=true
   - DB_USER=postgres
   - DB_PASSWORD=Pass2020!
   - DB_HOST=postgresd-dummy-node
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - GRPC_PORT=9095
   - SYSTEM=dummynode
  restart: always
  networks:
   - ukama-net
  depends_on:
   - postgresd-dummy-node

networks:
 ukama-net:
  external: true
  name: services_ukama-net
