// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/ukama/ukama/systems/registry/site/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// ProvisionClient is an autogenerated mock type for the ProvisionClient type
type ProvisionClient struct {
	mock.Mock
}

// Reconcile provides a mock function with given fields: _a0, _a1
func (_m *ProvisionClient) Reconcile(_a0 context.Context, _a1 client.ProvisionNode) (client.ProvisionResult, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 client.ProvisionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ProvisionNode) (client.ProvisionResult, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ProvisionNode) client.ProvisionResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(client.ProvisionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ProvisionNode) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProvisionClient creates a new instance of ProvisionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvisionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProvisionClient {
	mock := &ProvisionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
