// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// provisionClient is an autogenerated mock type for the provisionClient type
type provisionClient struct {
	mock.Mock
}

// Reconcile provides a mock function with given fields: _a0, _a1
func (_m *provisionClient) Reconcile(_a0 context.Context, _a1 server.provisionNode) (server.provisionResult, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 server.provisionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, server.provisionNode) (server.provisionResult, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, server.provisionNode) server.provisionResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(server.provisionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, server.provisionNode) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newProvisionClient creates a new instance of provisionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newProvisionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *provisionClient {
	mock := &provisionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
