/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2022-present, Ukama Inc.
 */

all : addons

addons:
	@echo Building addons for Ukama

distclean:
	@echo Dummy distclean
clean: 
	@echo Dummy clean for addons
