version: "3.7"

services:
  bff:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - AUTH_URL=http://kratos:4433
      - NUCLEUS_API_GW=http://api-gateway-nucleus:8080
      - INIT_API_GW=http://api-gateway-init:8080
      - INVENTORY_API_GW=http://api-gateway-inventory:8080
      - ENCRYPTION_KEY=the-key-has-to-be-32-bytes-long!
      - STORAGE_KEY=ukama
      - CONSOLE_APP_URL=http://console:3000
      - AUTH_APP_URL=http://app:4455
      - GATEWAY_PORT=8080
      - SUBSCRIPTIONS_PORT=8081
      - AUTH_APP_URL=http://localhost:4455
      - PLAYGROUND_URL=http://localhost:8080
      - CONSOLE_APP_URL=http://localhost:3000
    networks:
      - ukama-net

networks:
  ukama-net:
    external: true
    name: services_ukama-net
