// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/hub/distributor/pb/gen"
)

// chunker is an autogenerated mock type for the chunker type
type chunker struct {
	mock.Mock
}

// CreateChunk provides a mock function with given fields: in
func (_m *chunker) CreateChunk(in *gen.CreateChunkRequest) (*gen.CreateChunkResponse, error) {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for CreateChunk")
	}

	var r0 *gen.CreateChunkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.CreateChunkRequest) (*gen.CreateChunkResponse, error)); ok {
		return rf(in)
	}
	if rf, ok := ret.Get(0).(func(*gen.CreateChunkRequest) *gen.CreateChunkResponse); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.CreateChunkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.CreateChunkRequest) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newChunker creates a new instance of chunker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newChunker(t interface {
	mock.TestingT
	Cleanup(func())
}) *chunker {
	mock := &chunker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
