@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container_Boundary(c1, "Base Rate") {
    Container(service,"GetBaseRates","go, grpc, gorm")
    ContainerDb(database, "Database", "PostgreSQL", "Store rates")

    Rel_R(Call, service, "{{ *Country, Provider, To, From, SimType }}")
    Rel_R(service, database, "Read base rates data")
}

@enduml