import { REGISTRY_API_URL, SUBSCRIBER_API_URL } from "../constants/index";

export const SERVER = {
    REGISTRY_USERS_API_URL: `${REGISTRY_API_URL}/v1/users`,
    REGISTRY_ORGS_API_URL: `${REGISTRY_API_URL}/v1/orgs`,
    REGISTRY_NETWORKS_API_URL: `${REGISTRY_API_URL}/v1/networks`,
    SUBSCRIBER_REGISTRY_API_URL: `${SUBSCRIBER_API_URL}/v1/subscriber`,
    GET_CONNECTED_USERS: `${REGISTRY_API_URL}/user/get_conneted_users`,
    GET_DATA_USAGE: `${REGISTRY_API_URL}/data/data_usage`,
    GET_DATA_BILL: `${REGISTRY_API_URL}/data/data_bill`,
    GET_ALERTS: `${REGISTRY_API_URL}/alert/get_alerts`,
    GET_NODES: `${REGISTRY_API_URL}/node/get_nodes`,
    GET_RESIDENTS: `${REGISTRY_API_URL}/resident/get_residents`,
    GET_ESIMS: `${REGISTRY_API_URL}/esims/get_esims`,
    POST_ACTIVE_USER: `${REGISTRY_API_URL}/user/active_user`,
    GET_USERS: `${REGISTRY_API_URL}/user/get_users`,
    POST_ADD_NODE: `${REGISTRY_API_URL}/node/add_node`,
    GET_CURRENT_BILL: `${REGISTRY_API_URL}/bill/get_current_bill`,
    GET_BILL_HISTORY: `${REGISTRY_API_URL}/bill/get_bill_history`,
    GET_NETWORK: `${REGISTRY_API_URL}/network/get_network`,
    POST_UPDATE_USER: `${REGISTRY_API_URL}/user/update_user`,
    POST_DEACTIVATE_USER: `${REGISTRY_API_URL}/user/deactivate_user`,
    POST_UPDATE_NODE: `${REGISTRY_API_URL}/node/update_node`,
    POST_DELETE_NODE: `${REGISTRY_API_URL}/node/delete_node`,
    GET_USER: `${REGISTRY_API_URL}/user/get_user`,
    ORG: `${REGISTRY_API_URL}/orgs`,
    GET_SOFTWARE_LOGS: `${REGISTRY_API_URL}/software_logs`,
    GET_NODE_APPS: `${REGISTRY_API_URL}/node_apps`,
    GET_NODE_DETAIL: `${REGISTRY_API_URL}/node/node_details`,
    GET_NODE_META_DATA: `${REGISTRY_API_URL}/node/meta_data`,
    GET_NODE_PHYSICAL_HEALTH: `${REGISTRY_API_URL}/node/physical_health`,
    GET_NODE_RF_KPI: `${REGISTRY_API_URL}/node/rf_kpis`,
    GET_NODE_NETWORK: `${REGISTRY_API_URL}/node/get_network`,
    GET_THROUGHPUT_METRICS: `${REGISTRY_API_URL}/metrics/throughput`,
    GET_USERS_ATTACHED_METRICS: `${REGISTRY_API_URL}/metrics/user`,
    GET_CPU_USAGE_METRICS: `${REGISTRY_API_URL}/metrics/cpu`,
    GET_TEMPERATURE_METRICS: `${REGISTRY_API_URL}/metrics/temperature`,
    GET_IO_METRICS: `${REGISTRY_API_URL}/metrics/io`,
    GET_MEMORY_USAGE_METRICS: `${REGISTRY_API_URL}/metrics/memory`,
    GET_IDENTITY: `https://kratos-admin.dev.ukama.com/admin/identities`,
};

export const getMetricUri = (
    orgId: string,
    nodeId: string,
    endpoint: string,
): string => `${SERVER.ORG}/${orgId}/nodes/${nodeId}/metrics/${endpoint}`;
