name: Run sonar scan
description: Build application and image

inputs:
  project-key:
    description: Sonarcloud project key
    required: true
  sonar-token:
    description: API token for sonarcloud
    required: true
  working-directory:
    description: The working directory for the application
    required: true
  github-bot-token:
    description: The github bot token
    required: true

runs:
  using: "composite"
  steps:

  - uses: actions/cache@v4
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
        /opt/sonar-scanner/.sonar/cache
      key: ${{ runner.os }}-go-ukama
      restore-keys: |
        ${{ runner.os }}-go-

  - name: Download code coverage results
    uses: actions/download-artifact@v4
    with:
      name: code-coverage-${{ inputs.project-Key }}-${{ github.run_number }}
      path: ${{ inputs.working-directory }}

  - name: SonarCloud Scan
    uses: sonarsource/sonarcloud-github-action@v2
    env:
      GITHUB_TOKEN: ${{ inputs.github-bot-token }}
      SONAR_TOKEN: ${{ inputs.sonar-token }}
    with:
      projectBaseDir:  ${{ inputs.working-directory }}
      args: >
        -Dsonar.organization=ukama
        -Dsonar.projectKey=${{ inputs.project-key }}
        -Dsonar.projectName=${{ inputs.working-directory }}
        -Dsonar.go.coverage.reportPaths=code-coverage-${{ inputs.project-Key }}-${{ github.run_number }}.out
        -Dsonar.test.exclusions=tests/**
        -Dsonar.tests=tests/
        -Dsonar.verbose=true
        -Dsonar.sources=.
        -Dsonar.exclusions=**/*_test.go,mocks/**,pb/**,test/**,go.mod,go.sum
        -Dsonar.tests=.
        -Dsonar.test.inclusions=**/*_test.go
