/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nodeEvent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "nodeEvent.pb-c.h"
void   ukama__events__v1__node_online_event__init
                     (Ukama__Events__V1__NodeOnlineEvent         *message)
{
  static const Ukama__Events__V1__NodeOnlineEvent init_value = UKAMA__EVENTS__V1__NODE_ONLINE_EVENT__INIT;
  *message = init_value;
}
size_t ukama__events__v1__node_online_event__get_packed_size
                     (const Ukama__Events__V1__NodeOnlineEvent *message)
{
  assert(message->base.descriptor == &ukama__events__v1__node_online_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ukama__events__v1__node_online_event__pack
                     (const Ukama__Events__V1__NodeOnlineEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ukama__events__v1__node_online_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ukama__events__v1__node_online_event__pack_to_buffer
                     (const Ukama__Events__V1__NodeOnlineEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ukama__events__v1__node_online_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ukama__Events__V1__NodeOnlineEvent *
       ukama__events__v1__node_online_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ukama__Events__V1__NodeOnlineEvent *)
     protobuf_c_message_unpack (&ukama__events__v1__node_online_event__descriptor,
                                allocator, len, data);
}
void   ukama__events__v1__node_online_event__free_unpacked
                     (Ukama__Events__V1__NodeOnlineEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ukama__events__v1__node_online_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ukama__events__v1__node_offline_event__init
                     (Ukama__Events__V1__NodeOfflineEvent         *message)
{
  static const Ukama__Events__V1__NodeOfflineEvent init_value = UKAMA__EVENTS__V1__NODE_OFFLINE_EVENT__INIT;
  *message = init_value;
}
size_t ukama__events__v1__node_offline_event__get_packed_size
                     (const Ukama__Events__V1__NodeOfflineEvent *message)
{
  assert(message->base.descriptor == &ukama__events__v1__node_offline_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ukama__events__v1__node_offline_event__pack
                     (const Ukama__Events__V1__NodeOfflineEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ukama__events__v1__node_offline_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ukama__events__v1__node_offline_event__pack_to_buffer
                     (const Ukama__Events__V1__NodeOfflineEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ukama__events__v1__node_offline_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ukama__Events__V1__NodeOfflineEvent *
       ukama__events__v1__node_offline_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ukama__Events__V1__NodeOfflineEvent *)
     protobuf_c_message_unpack (&ukama__events__v1__node_offline_event__descriptor,
                                allocator, len, data);
}
void   ukama__events__v1__node_offline_event__free_unpacked
                     (Ukama__Events__V1__NodeOfflineEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ukama__events__v1__node_offline_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ukama__events__v1__node_online_event__field_descriptors[6] =
{
  {
    "nodeId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ukama__Events__V1__NodeOnlineEvent, nodeid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeIp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ukama__Events__V1__NodeOnlineEvent, nodeip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodePort",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ukama__Events__V1__NodeOnlineEvent, nodeport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meshIp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ukama__Events__V1__NodeOnlineEvent, meship),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meshPort",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ukama__Events__V1__NodeOnlineEvent, meshport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meshHostName",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ukama__Events__V1__NodeOnlineEvent, meshhostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ukama__events__v1__node_online_event__field_indices_by_name[] = {
  5,   /* field[5] = meshHostName */
  3,   /* field[3] = meshIp */
  4,   /* field[4] = meshPort */
  0,   /* field[0] = nodeId */
  1,   /* field[1] = nodeIp */
  2,   /* field[2] = nodePort */
};
static const ProtobufCIntRange ukama__events__v1__node_online_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ukama__events__v1__node_online_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ukama.events.v1.NodeOnlineEvent",
  "NodeOnlineEvent",
  "Ukama__Events__V1__NodeOnlineEvent",
  "ukama.events.v1",
  sizeof(Ukama__Events__V1__NodeOnlineEvent),
  6,
  ukama__events__v1__node_online_event__field_descriptors,
  ukama__events__v1__node_online_event__field_indices_by_name,
  1,  ukama__events__v1__node_online_event__number_ranges,
  (ProtobufCMessageInit) ukama__events__v1__node_online_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ukama__events__v1__node_offline_event__field_descriptors[1] =
{
  {
    "nodeId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ukama__Events__V1__NodeOfflineEvent, nodeid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ukama__events__v1__node_offline_event__field_indices_by_name[] = {
  0,   /* field[0] = nodeId */
};
static const ProtobufCIntRange ukama__events__v1__node_offline_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ukama__events__v1__node_offline_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ukama.events.v1.NodeOfflineEvent",
  "NodeOfflineEvent",
  "Ukama__Events__V1__NodeOfflineEvent",
  "ukama.events.v1",
  sizeof(Ukama__Events__V1__NodeOfflineEvent),
  1,
  ukama__events__v1__node_offline_event__field_descriptors,
  ukama__events__v1__node_offline_event__field_indices_by_name,
  1,  ukama__events__v1__node_offline_event__number_ranges,
  (ProtobufCMessageInit) ukama__events__v1__node_offline_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
