// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	metrics "github.com/ukama/ukama/systems/common/metrics"
)

// MetricsPusher is an autogenerated mock type for the MetricsPusher type
type MetricsPusher struct {
	mock.Mock
}

// CollectAndPushSimMetrics provides a mock function with given fields: configMetrics, selectedMetric, Value, Labels, systemName
func (_m *MetricsPusher) CollectAndPushSimMetrics(configMetrics []metrics.MetricConfig, selectedMetric string, Value float64, Labels map[string]string, systemName string) error {
	ret := _m.Called(configMetrics, selectedMetric, Value, Labels, systemName)

	if len(ret) == 0 {
		panic("no return value specified for CollectAndPushSimMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]metrics.MetricConfig, string, float64, map[string]string, string) error); ok {
		r0 = rf(configMetrics, selectedMetric, Value, Labels, systemName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPushMetricsHost provides a mock function with no fields
func (_m *MetricsPusher) GetPushMetricsHost() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPushMetricsHost")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMetricsPusher creates a new instance of MetricsPusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsPusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsPusher {
	mock := &MetricsPusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
