// Code generated by mockery v2.21.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	providers "github.com/ukama/ukama/systems/subscriber/sim-manager/pkg/clients/providers"
)

// PackageClient is an autogenerated mock type for the PackageClient type
type PackageClient struct {
	mock.Mock
}

// GetPackageInfo provides a mock function with given fields: uuid
func (_m *PackageClient) GetPackageInfo(uuid string) (*providers.PackageInfo, error) {
	ret := _m.Called(uuid)

	var r0 *providers.PackageInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*providers.PackageInfo, error)); ok {
		return rf(uuid)
	}
	if rf, ok := ret.Get(0).(func(string) *providers.PackageInfo); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.PackageInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPackageClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewPackageClient creates a new instance of PackageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPackageClient(t mockConstructorTestingTNewPackageClient) *PackageClient {
	mock := &PackageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
