// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	db "github.com/ukama/ukama/systems/subscriber/sim-manager/pkg/db"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/ukama/ukama/systems/common/uuid"
)

// PackageRepo is an autogenerated mock type for the PackageRepo type
type PackageRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: pkg, nestedFunc
func (_m *PackageRepo) Add(pkg *db.Package, nestedFunc func(*db.Package, *gorm.DB) error) error {
	ret := _m.Called(pkg, nestedFunc)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.Package, func(*db.Package, *gorm.DB) error) error); ok {
		r0 = rf(pkg, nestedFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: packageId, nestedFunc
func (_m *PackageRepo) Delete(packageId uuid.UUID, nestedFunc func(uuid.UUID, *gorm.DB) error) error {
	ret := _m.Called(packageId, nestedFunc)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, func(uuid.UUID, *gorm.DB) error) error); ok {
		r0 = rf(packageId, nestedFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: packageId
func (_m *PackageRepo) Get(packageId uuid.UUID) (*db.Package, error) {
	ret := _m.Called(packageId)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *db.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*db.Package, error)); ok {
		return rf(packageId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *db.Package); ok {
		r0 = rf(packageId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(packageId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySim provides a mock function with given fields: simId
func (_m *PackageRepo) GetBySim(simId uuid.UUID) ([]db.Package, error) {
	ret := _m.Called(simId)

	if len(ret) == 0 {
		panic("no return value specified for GetBySim")
	}

	var r0 []db.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]db.Package, error)); ok {
		return rf(simId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []db.Package); ok {
		r0 = rf(simId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(simId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: simId, dataPlanId, fromStartDate, toSartDate, fromEndDate, toEndDate, isActive, asExpired, count, sort
func (_m *PackageRepo) List(simId string, dataPlanId string, fromStartDate string, toSartDate string, fromEndDate string, toEndDate string, isActive bool, asExpired bool, count uint32, sort bool) ([]db.Package, error) {
	ret := _m.Called(simId, dataPlanId, fromStartDate, toSartDate, fromEndDate, toEndDate, isActive, asExpired, count, sort)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, bool, bool, uint32, bool) ([]db.Package, error)); ok {
		return rf(simId, dataPlanId, fromStartDate, toSartDate, fromEndDate, toEndDate, isActive, asExpired, count, sort)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, bool, bool, uint32, bool) []db.Package); ok {
		r0 = rf(simId, dataPlanId, fromStartDate, toSartDate, fromEndDate, toEndDate, isActive, asExpired, count, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string, bool, bool, uint32, bool) error); ok {
		r1 = rf(simId, dataPlanId, fromStartDate, toSartDate, fromEndDate, toEndDate, isActive, asExpired, count, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: pkg, nestedFunc
func (_m *PackageRepo) Update(pkg *db.Package, nestedFunc func(*db.Package, *gorm.DB) error) error {
	ret := _m.Called(pkg, nestedFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.Package, func(*db.Package, *gorm.DB) error) error); ok {
		r0 = rf(pkg, nestedFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPackageRepo creates a new instance of PackageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPackageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PackageRepo {
	mock := &PackageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
