// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// RunningOrgClient is an autogenerated mock type for the RunningOrgClient type
type RunningOrgClient struct {
	mock.Mock
}

// GetRunningOrg provides a mock function with given fields:
func (_m *RunningOrgClient) GetRunningOrg() (uuid.UUID, error) {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRunningOrgClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewRunningOrgClient creates a new instance of RunningOrgClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRunningOrgClient(t mockConstructorTestingTNewRunningOrgClient) *RunningOrgClient {
	mock := &RunningOrgClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
