// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/subscriber/subscriber-registry/pb/gen"
)

// SubscriberRegistryClientProvider is an autogenerated mock type for the SubscriberRegistryClientProvider type
type SubscriberRegistryClientProvider struct {
	mock.Mock
}

// GetClient provides a mock function with given fields:
func (_m *SubscriberRegistryClientProvider) GetClient() (gen.SubscriberRegistryServiceClient, error) {
	ret := _m.Called()

	var r0 gen.SubscriberRegistryServiceClient
	if rf, ok := ret.Get(0).(func() gen.SubscriberRegistryServiceClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gen.SubscriberRegistryServiceClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSubscriberRegistryClientProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewSubscriberRegistryClientProvider creates a new instance of SubscriberRegistryClientProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubscriberRegistryClientProvider(t mockConstructorTestingTNewSubscriberRegistryClientProvider) *SubscriberRegistryClientProvider {
	mock := &SubscriberRegistryClientProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
