// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/data-plan/base-rate/pkg/db"
	uuid "github.com/ukama/ukama/systems/common/uuid"

)

// BaseRateRepo is an autogenerated mock type for the BaseRateRepo type
type BaseRateRepo struct {
	mock.Mock
}

// GetBaseRate provides a mock function with given fields: _a0
func (_m *BaseRateRepo) GetBaseRate(_a0 uuid.UUID) (*db.Rate, error) {
	ret := _m.Called(_a0)

	var r0 *db.Rate
	if rf, ok := ret.Get(0).(func(uuid.UUID) *db.Rate); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Rate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBaseRates provides a mock function with given fields: country, network, effectiveAt, simType
func (_m *BaseRateRepo) GetBaseRates(country string, network string, effectiveAt string, simType string) ([]db.Rate, error) {
	ret := _m.Called(country, network, effectiveAt, simType)

	var r0 []db.Rate
	if rf, ok := ret.Get(0).(func(string, string, string, string) []db.Rate); ok {
		r0 = rf(country, network, effectiveAt, simType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Rate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(country, network, effectiveAt, simType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadBaseRates provides a mock function with given fields: rateList
func (_m *BaseRateRepo) UploadBaseRates(rateList []db.Rate) error {
	ret := _m.Called(rateList)

	var r0 error
	if rf, ok := ret.Get(0).(func([]db.Rate) error); ok {
		r0 = rf(rateList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBaseRateRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewBaseRateRepo creates a new instance of BaseRateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBaseRateRepo(t mockConstructorTestingTNewBaseRateRepo) *BaseRateRepo {
	mock := &BaseRateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
