// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/notification/mailer/pb/gen"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// GetEmailById provides a mock function with given fields: mailId
func (_m *Mailer) GetEmailById(mailId string) (*gen.GetEmailByIdResponse, error) {
	ret := _m.Called(mailId)

	if len(ret) == 0 {
		panic("no return value specified for GetEmailById")
	}

	var r0 *gen.GetEmailByIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*gen.GetEmailByIdResponse, error)); ok {
		return rf(mailId)
	}
	if rf, ok := ret.Get(0).(func(string) *gen.GetEmailByIdResponse); ok {
		r0 = rf(mailId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetEmailByIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(mailId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendEmail provides a mock function with given fields: req
func (_m *Mailer) SendEmail(req *gen.SendEmailRequest) (*gen.SendEmailResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 *gen.SendEmailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.SendEmailRequest) (*gen.SendEmailResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.SendEmailRequest) *gen.SendEmailResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.SendEmailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.SendEmailRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
