BOOTSTRAP_APP=yes
CONFIGD_APP=yes
DEVICED_APP=yes
LOOKOUTD_APP=yes
MESHD_APP=yes
METRICSD_APP=yes
NODED_APP=yes
NOTIFYD_APP=yes
RLOG_APP=yes
STARTERD_APP=no
WIMCD_APP=yes
FEMD_APP=yes
POWER_APP=yes
BACKHAUL_APP=no
GPS_APP=no
