// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	db "github.com/ukama/ukama/systems/registry/network/pkg/db"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/ukama/ukama/systems/common/uuid"
)

// SiteRepo is an autogenerated mock type for the SiteRepo type
type SiteRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: site, nestedFunc
func (_m *SiteRepo) Add(site *db.Site, nestedFunc func(*db.Site, *gorm.DB) error) error {
	ret := _m.Called(site, nestedFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.Site, func(*db.Site, *gorm.DB) error) error); ok {
		r0 = rf(site, nestedFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *SiteRepo) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *SiteRepo) Get(id uuid.UUID) (*db.Site, error) {
	ret := _m.Called(id)

	var r0 *db.Site
	if rf, ok := ret.Get(0).(func(uuid.UUID) *db.Site); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Site)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: netID, siteName
func (_m *SiteRepo) GetByName(netID uuid.UUID, siteName string) (*db.Site, error) {
	ret := _m.Called(netID, siteName)

	var r0 *db.Site
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *db.Site); ok {
		r0 = rf(netID, siteName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Site)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(netID, siteName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNetwork provides a mock function with given fields: netID
func (_m *SiteRepo) GetByNetwork(netID uuid.UUID) ([]db.Site, error) {
	ret := _m.Called(netID)

	var r0 []db.Site
	if rf, ok := ret.Get(0).(func(uuid.UUID) []db.Site); ok {
		r0 = rf(netID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Site)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(netID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSiteRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewSiteRepo creates a new instance of SiteRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSiteRepo(t mockConstructorTestingTNewSiteRepo) *SiteRepo {
	mock := &SiteRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
