// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	notification "github.com/ukama/ukama/systems/common/rest/client/notification"
)

// MailerClient is an autogenerated mock type for the MailerClient type
type MailerClient struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: body
func (_m *MailerClient) SendEmail(body notification.SendEmailReq) error {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.SendEmailReq) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailerClient creates a new instance of MailerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailerClient {
	mock := &MailerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
