// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	registry "github.com/ukama/ukama/systems/common/rest/client/registry"
)

// NodeClient is an autogenerated mock type for the NodeClient type
type NodeClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *NodeClient) Add(_a0 registry.AddNodeRequest) (*registry.NodeInfo, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *registry.NodeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(registry.AddNodeRequest) (*registry.NodeInfo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(registry.AddNodeRequest) *registry.NodeInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.NodeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(registry.AddNodeRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddToSite provides a mock function with given fields: _a0, _a1
func (_m *NodeClient) AddToSite(_a0 string, _a1 registry.AddToSiteRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddToSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, registry.AddToSiteRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Attach provides a mock function with given fields: _a0, _a1
func (_m *NodeClient) Attach(_a0 string, _a1 registry.AttachNodesRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, registry.AttachNodesRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *NodeClient) Delete(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Detach provides a mock function with given fields: _a0
func (_m *NodeClient) Detach(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Detach")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *NodeClient) Get(_a0 string) (*registry.NodeInfo, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *registry.NodeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*registry.NodeInfo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *registry.NodeInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.NodeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with no fields
func (_m *NodeClient) GetAll() (*registry.Nodes, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *registry.Nodes
	var r1 error
	if rf, ok := ret.Get(0).(func() (*registry.Nodes, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *registry.Nodes); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.Nodes)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodesBySite provides a mock function with given fields: _a0
func (_m *NodeClient) GetNodesBySite(_a0 string) (*registry.NodesBySite, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetNodesBySite")
	}

	var r0 *registry.NodesBySite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*registry.NodesBySite, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *registry.NodesBySite); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.NodesBySite)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFromSite provides a mock function with given fields: _a0
func (_m *NodeClient) RemoveFromSite(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNodeClient creates a new instance of NodeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeClient {
	mock := &NodeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
