// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	operatoragent "github.com/ukama/ukama/systems/common/rest/client/operatoragent"
)

// OperatorAgentClient is an autogenerated mock type for the OperatorAgentClient type
type OperatorAgentClient struct {
	mock.Mock
}

// ActivateSim provides a mock function with given fields: iccid
func (_m *OperatorAgentClient) ActivateSim(iccid string) error {
	ret := _m.Called(iccid)

	if len(ret) == 0 {
		panic("no return value specified for ActivateSim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(iccid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BindSim provides a mock function with given fields: iccid
func (_m *OperatorAgentClient) BindSim(iccid string) (*operatoragent.OperatorSimInfo, error) {
	ret := _m.Called(iccid)

	if len(ret) == 0 {
		panic("no return value specified for BindSim")
	}

	var r0 *operatoragent.OperatorSimInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*operatoragent.OperatorSimInfo, error)); ok {
		return rf(iccid)
	}
	if rf, ok := ret.Get(0).(func(string) *operatoragent.OperatorSimInfo); ok {
		r0 = rf(iccid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operatoragent.OperatorSimInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iccid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateSim provides a mock function with given fields: iccid
func (_m *OperatorAgentClient) DeactivateSim(iccid string) error {
	ret := _m.Called(iccid)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateSim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(iccid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSimInfo provides a mock function with given fields: iccid
func (_m *OperatorAgentClient) GetSimInfo(iccid string) (*operatoragent.OperatorSimInfo, error) {
	ret := _m.Called(iccid)

	if len(ret) == 0 {
		panic("no return value specified for GetSimInfo")
	}

	var r0 *operatoragent.OperatorSimInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*operatoragent.OperatorSimInfo, error)); ok {
		return rf(iccid)
	}
	if rf, ok := ret.Get(0).(func(string) *operatoragent.OperatorSimInfo); ok {
		r0 = rf(iccid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operatoragent.OperatorSimInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iccid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsages provides a mock function with given fields: iccid, cdrType, from, to, region
func (_m *OperatorAgentClient) GetUsages(iccid string, cdrType string, from string, to string, region string) (map[string]interface{}, map[string]interface{}, error) {
	ret := _m.Called(iccid, cdrType, from, to, region)

	if len(ret) == 0 {
		panic("no return value specified for GetUsages")
	}

	var r0 map[string]interface{}
	var r1 map[string]interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) (map[string]interface{}, map[string]interface{}, error)); ok {
		return rf(iccid, cdrType, from, to, region)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) map[string]interface{}); ok {
		r0 = rf(iccid, cdrType, from, to, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string) map[string]interface{}); ok {
		r1 = rf(iccid, cdrType, from, to, region)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string, string) error); ok {
		r2 = rf(iccid, cdrType, from, to, region)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TerminateSim provides a mock function with given fields: iccid
func (_m *OperatorAgentClient) TerminateSim(iccid string) error {
	ret := _m.Called(iccid)

	if len(ret) == 0 {
		panic("no return value specified for TerminateSim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(iccid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOperatorAgentClient creates a new instance of OperatorAgentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperatorAgentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperatorAgentClient {
	mock := &OperatorAgentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
