// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeHealthServer is an autogenerated mock type for the UnsafeHealthServer type
type UnsafeHealthServer struct {
	mock.Mock
}

// mustEmbedUnimplementedHealthServer provides a mock function with no fields
func (_m *UnsafeHealthServer) mustEmbedUnimplementedHealthServer() {
	_m.Called()
}

// NewUnsafeHealthServer creates a new instance of UnsafeHealthServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeHealthServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeHealthServer {
	mock := &UnsafeHealthServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
