name: Init git vars 
description: Initialize extra git vars

outputs:
  branch:
    description: The branch name
    value: ${{ steps.vars_step.outputs.branch }}

  sha-short:
    description: Short git SHA 
    value: ${{ steps.vars_step.outputs.sha-short }}

    
runs:
  using: "composite"
  steps:  

    - name: Init vars
      shell: bash
      id: vars_step
      run: |
        echo "::set-output name=sha-short::$(git rev-parse --short=7 HEAD)"
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
