name: Init git vars 
description: Initialize extra git vars

outputs:
  branch:
    description: The branch name
    value: ${{ steps.vars_step.outputs.branch }}

  sha-short:
    description: Short git SHA 
    value: ${{ steps.vars_step.outputs.sha-short }}

  tag: 
    description: The tag name
    value: ${{ steps.vars_step.outputs.tag }}

    
runs:
  using: "composite"
  steps:  
    - name: Init vars
      shell: bash
      id: vars_step
      run: |
        echo "::set-output name=sha-short::$(git rev-parse --short=7 HEAD)"
        export CURR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo  "::set-output name=branch::${CURR_BRANCH:-unknown}"
        export CURR_TAG=$(git tag --points-at HEAD)
        echo "::set-output name=tag::${CURR_TAG:-unknown-tag}"
