# Config file for mesh.d

[local-config]
    remote-ip-file = "/ukama/configs/meshd/ip_file"
    local-hostname = "localhost"
    cert           = "/ukama/configs/meshd/cert.crt"
    key            = "/ukama/configs/meshd/pem.key"
