name: Compile app
description: Compile application and run tests.

inputs:
  project-key:
    description: Sonarcloud project key
    required: true
  working-directory:
    description: The working directory for the application
    required: true
  github-bot-token:
    description: The github bot token
    required: true

runs:
  using: "composite"
  steps:
  - name: Init vars
    id: vars_step
    uses: ./.github/actions/git-vars

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: '>=1.19.0'
      cache-dependency-path: |
        **/go.sum


  - name: Granting private modules access
    shell: bash
    run: |
      git config --global url."https://none:${{ inputs.github-bot-token }}@github.com/ukama".insteadOf "https://github.com/ukama"

  - uses: actions/cache@v4
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
        /opt/sonar-scanner/.sonar/cache
      key: ${{ runner.os }}-go-ukama
      restore-keys: |
        ${{ runner.os }}-go-

  - name: Build
    shell: bash
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    run: make build
    working-directory: ${{ inputs.working-directory }}

  - name: Test
    shell: bash
    run: go test -v ./... -coverprofile=code-coverage-${{ inputs.project-Key }}-${{ github.run_number }}.out
    working-directory: ${{ inputs.working-directory }}

  - name: Archive code coverage results
    uses: actions/upload-artifact@v4
    with:
      name: code-coverage-${{ inputs.project-Key }}-${{ github.run_number }}
      path: ${{ inputs.working-directory }}/code-coverage-${{ inputs.project-Key }}-${{ github.run_number }}.out
