[build-from]
	rootfs="default"     # default is busybox minimal capp config
	contained="default"  # default namespace, cgroup, etc.

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/controller/test"
	cmd="true"
	bin_from="/nodes/apps/controller/test/vedirect_emulator.py"
	bin_to="/sbin"

# Following are use to create config.json file which is used by starter.d to start 
# the capp within ukamaOS and pkg everything
[capp-exec]
	name="controlleremu"
	version="latest"
	bin="vedirect_emulator.py"
	path="/sbin" # path where the exec should be. Mathches build.bin_to
	
# Final output format for capp
[capp-output]
	format="tar.gz"
