[build-from]
	rootfs="default"     # default is busybox minimal capp config
	contained="default"  # default namespace, cgroup, etc.

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/init-network"
	cmd="make"
	bin_from="/nodes/apps/init-network/init-network"
	bin_to="/sbin"

[build-rootfs]
	mkdir="/conf"

[build-conf]
	from="/nodes/configs/apps/init-network/config/config.toml"
	to="/ukama/configs/init-network"

[capp-exec]
	name="init-network"
	version="latest"
	bin="init-network"
	path="/sbin"
	args="--config /ukama/configs/init-network/config.toml"

# Final output format for capp
[capp-output]
	format="tar.gz"
