[build-from]
	rootfs="default"
	contained="default"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/system/lifecycled"
	cmd="make"
	bin_from="/nodes/ukamaOS/distro/system/lifecycled/lifecycle.d"
	bin_to="/sbin"

[capp-exec]
	name="lifecycled"
	version="latest"
	bin="lifecycle.d"
	path="/sbin"

[capp-output]
	format="tar.gz"
