[build-from]
	rootfs="default"
	contained="default"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/pcrf"
	cmd="make"
	bin_from="/nodes/apps/pcrf/bin/pcrf"
	bin_to="/sbin"

[capp-exec]
	name="pcrf"
	version="latest"
	bin="pcrf"
	path="/sbin"

[capp-output]
	format="tar.gz"
