// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/subscriber/registry/pb/gen"
)

// subscriber is an autogenerated mock type for the subscriber type
type subscriber struct {
	mock.Mock
}

// AddSubscriber provides a mock function with given fields: ctx, req
func (_m *subscriber) AddSubscriber(ctx context.Context, req *gen.AddSubscriberRequest) (*gen.AddSubscriberResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddSubscriber")
	}

	var r0 *gen.AddSubscriberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.AddSubscriberRequest) (*gen.AddSubscriberResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.AddSubscriberRequest) *gen.AddSubscriberResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.AddSubscriberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.AddSubscriberRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSubscriber provides a mock function with given fields: ctx, sid
func (_m *subscriber) DeleteSubscriber(ctx context.Context, sid string) (*gen.DeleteSubscriberResponse, error) {
	ret := _m.Called(ctx, sid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscriber")
	}

	var r0 *gen.DeleteSubscriberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.DeleteSubscriberResponse, error)); ok {
		return rf(ctx, sid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.DeleteSubscriberResponse); ok {
		r0 = rf(ctx, sid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DeleteSubscriberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNetwork provides a mock function with given fields: ctx, networkId
func (_m *subscriber) GetByNetwork(ctx context.Context, networkId string) (*gen.GetByNetworkResponse, error) {
	ret := _m.Called(ctx, networkId)

	if len(ret) == 0 {
		panic("no return value specified for GetByNetwork")
	}

	var r0 *gen.GetByNetworkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.GetByNetworkResponse, error)); ok {
		return rf(ctx, networkId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.GetByNetworkResponse); ok {
		r0 = rf(ctx, networkId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetByNetworkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, networkId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriber provides a mock function with given fields: ctx, sid
func (_m *subscriber) GetSubscriber(ctx context.Context, sid string) (*gen.GetSubscriberResponse, error) {
	ret := _m.Called(ctx, sid)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriber")
	}

	var r0 *gen.GetSubscriberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.GetSubscriberResponse, error)); ok {
		return rf(ctx, sid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.GetSubscriberResponse); ok {
		r0 = rf(ctx, sid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetSubscriberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriberByEmail provides a mock function with given fields: ctx, sEmail
func (_m *subscriber) GetSubscriberByEmail(ctx context.Context, sEmail string) (*gen.GetSubscriberByEmailResponse, error) {
	ret := _m.Called(ctx, sEmail)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriberByEmail")
	}

	var r0 *gen.GetSubscriberByEmailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.GetSubscriberByEmailResponse, error)); ok {
		return rf(ctx, sEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.GetSubscriberByEmailResponse); ok {
		r0 = rf(ctx, sEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetSubscriberByEmailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSubscriber provides a mock function with given fields: ctx, subscriber
func (_m *subscriber) UpdateSubscriber(ctx context.Context, subscriber *gen.UpdateSubscriberRequest) (*gen.UpdateSubscriberResponse, error) {
	ret := _m.Called(ctx, subscriber)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscriber")
	}

	var r0 *gen.UpdateSubscriberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateSubscriberRequest) (*gen.UpdateSubscriberResponse, error)); ok {
		return rf(ctx, subscriber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateSubscriberRequest) *gen.UpdateSubscriberResponse); ok {
		r0 = rf(ctx, subscriber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.UpdateSubscriberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateSubscriberRequest) error); ok {
		r1 = rf(ctx, subscriber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newSubscriber creates a new instance of subscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *subscriber {
	mock := &subscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
