/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshRegisterEvent.proto */

#ifndef PROTOBUF_C_meshRegisterEvent_2eproto__INCLUDED
#define PROTOBUF_C_meshRegisterEvent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MeshRegisterEvent MeshRegisterEvent;


/* --- enums --- */


/* --- messages --- */

struct  _MeshRegisterEvent
{
  ProtobufCMessage base;
  char *ip;
  int32_t port;
};
#define MESH_REGISTER_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mesh_register_event__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/* MeshRegisterEvent methods */
void   mesh_register_event__init
                     (MeshRegisterEvent         *message);
size_t mesh_register_event__get_packed_size
                     (const MeshRegisterEvent   *message);
size_t mesh_register_event__pack
                     (const MeshRegisterEvent   *message,
                      uint8_t             *out);
size_t mesh_register_event__pack_to_buffer
                     (const MeshRegisterEvent   *message,
                      ProtobufCBuffer     *buffer);
MeshRegisterEvent *
       mesh_register_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mesh_register_event__free_unpacked
                     (MeshRegisterEvent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MeshRegisterEvent_Closure)
                 (const MeshRegisterEvent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mesh_register_event__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshRegisterEvent_2eproto__INCLUDED */
