/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshRegisterEvent.proto */

#ifndef PROTOBUF_C_meshRegisterEvent_2eproto__INCLUDED
#define PROTOBUF_C_meshRegisterEvent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ukama__Events__V1__MeshRegisterEvent Ukama__Events__V1__MeshRegisterEvent;


/* --- enums --- */


/* --- messages --- */

struct  _Ukama__Events__V1__MeshRegisterEvent
{
  ProtobufCMessage base;
  char *ip;
  int32_t port;
};
#define UKAMA__EVENTS__V1__MESH_REGISTER_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ukama__events__v1__mesh_register_event__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/* Ukama__Events__V1__MeshRegisterEvent methods */
void   ukama__events__v1__mesh_register_event__init
                     (Ukama__Events__V1__MeshRegisterEvent         *message);
size_t ukama__events__v1__mesh_register_event__get_packed_size
                     (const Ukama__Events__V1__MeshRegisterEvent   *message);
size_t ukama__events__v1__mesh_register_event__pack
                     (const Ukama__Events__V1__MeshRegisterEvent   *message,
                      uint8_t             *out);
size_t ukama__events__v1__mesh_register_event__pack_to_buffer
                     (const Ukama__Events__V1__MeshRegisterEvent   *message,
                      ProtobufCBuffer     *buffer);
Ukama__Events__V1__MeshRegisterEvent *
       ukama__events__v1__mesh_register_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ukama__events__v1__mesh_register_event__free_unpacked
                     (Ukama__Events__V1__MeshRegisterEvent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ukama__Events__V1__MeshRegisterEvent_Closure)
                 (const Ukama__Events__V1__MeshRegisterEvent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ukama__events__v1__mesh_register_event__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshRegisterEvent_2eproto__INCLUDED */
