[build-from]
	base="alpine"
	version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/controller/test"
	cmd="true"
	bin_from="/nodes/apps/controller/controller/test/vedirect_emulator.py"
	bin_to="/sbin"

[app-exec]
	name="controlleremu"
	version="latest"
	bin="vedirect_emulator.py"
	path="/sbin"
	args="--mode realtime --city Goma"
	autostart="false"
	autorestart="true"
	startretries=5
	group="sys-service"

[app-exec.env]
	CONTROLLER_SERIAL_PORT="/tmp/victron-tty"
