[build-from]
	base="alpine"
	version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/controller"
	cmd="make"
	bin_from="/nodes/apps/controller/controllerd"
	bin_to="/sbin"

[app-exec]
	name="controller"
	version="latest"
	bin="controllerd"
	path="/sbin"
	autostart="false"
	autorestart="true"
	startretries=5
	group="sys-service"

[app-exec.env]
	CONTROLLER_DRIVER="victron"
	CONTROLLER_SERIAL_PORT="/tmp/victron-tty",
