[build-from]
    base="alpine"
    version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/femd"
	cmd="make"
	bin_from="/nodes/apps/femd/fem.d"
	bin_to="/sbin"

[build-conf]
    from="/nodes/configs/apps/femd/safety_config.json"
    to="/ukama/configs/femd"
    
[capp-exec]
	name="femd"
	version="latest"
	bin="fem.d"
	path="/sbin"
    args="--config /ukama/configs/femd/safety_config.json"
	autostart="false"
    autorestart="true"
    startretries=5
	group="service"
