[build-from]
    base="alpine"
    version="latest"

[build-compile]
    version="0.1"
    static=false
    source="/nodes/apps/gps"
    cmd="make"
    bin_from="/nodes/apps/gps/gps.d"
    bin_to="/sbin"

[app-exec]
    name="gpsd"
    version="latest"
    bin="gps.d"
    args=""
    path="/sbin"
    autostart=false
    autorestart=true
    startretries=5
    readiness=true
    group="service"

[app-exec.env]
    UKAMA_GPS_MODE="mock"
    UKAMA_GPS_COORDS="33.942810,-118.410000"
