[build-from]
	base="alpine"
	version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/switchd"
	cmd="make"
	bin_from="/nodes/apps/switchd/switch.d"
	bin_to="/sbin"

[app-exec]
	name="switch"
	version="latest"
	bin="switch.d"
	path="/sbin"
	autostart="false"
	autorestart="true"
	startretries=5
	group="service"

[app-exec.env]
	SWITCHD_DRIVER="tycon_snmp"
	SWITCHD_SNMP_HOST="127.0.0.1"
	SWITCHD_SNMP_PORT="1161"
	SWITCHD_TFTP_BIND_IP="0.0.0.0"
	SWITCHD_TFTP_PORT="1069"
	SWITCHD_TFTP_ROOT="/tmp/switchd/tftp"
	SWITCHD_NOTIFY_HOST="127.0.0.1"
	SWITCHD_NOTIFY_PORT="18010"
	SWITCHEMU_HTTP_PORT="18088"
	SWITCHEMU_SNMP_PORT="1161"
	SWITCHEMU_TFTP_PORT="1069"
	SWITCHEMU_BIND_ADDRESS="0.0.0.0"
	SWITCHEMU_NOTIFY_HOST="127.0.0.1"
	SWITCHEMU_NOTIFY_PORT="18010"
