name: Go Lint
description: Lint go code

inputs:
  working-directory:
    description: The working directory for the application
    required: true
  github-bot-token:
    description: The github bot token
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: |
             **/go.sum

      - name: Granting private modules access
        shell: bash
        run: |
            git config --global url."https://none:${{ inputs.github-bot-token }}@github.com/ukama".insteadOf "https://github.com/ukama"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
          working-directory: ${{ inputs.working-directory }}
