[LWM2M.Object]
Name = "Power"
Description1 = "This IPSO object should be used to report power measurements. It also provides resources for minimum and maximum measured values, as well as the minimum and maximum range that can be measured by the sensor. An example measurement unit is Watts. This object may be used for either real power or apparent power measurements."
ObjectID = 3328
ObjectURN = "urn:oma:lwm2m:ext:3328:1.1"
LWM2MVersion = 1
ObjectVersion = "1.1"
MultipleInstances = "Multiple"
Mandatory = "Optional"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "Sensor Value"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "Last or Current Measured Value from the Sensor."
[[LWM2M.Object.Resources.Item]]
Name = "Sensor Units"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Measurement Units Definition."

[[LWM2M.Object.Resources.Item]]
Name = "Min Measured Value"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The minimum value measured by the sensor since power ON or reset."

[[LWM2M.Object.Resources.Item]]
Name = "Max Measured Value"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The maximum value measured by the sensor since power ON or reset."

[[LWM2M.Object.Resources.Item]]
Name = "Min Range Value"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The minimum value that can be measured by the sensor."

[[LWM2M.Object.Resources.Item]]
Name = "Max Range Value"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "The maximum value that can be measured by the sensor."

[[LWM2M.Object.Resources.Item]]
Name = "Reset Min and Max Measured Values"
Operations = "E"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = ""
RangeEnumeration = ""
Units = ""
Description = "Reset the Min and Max Measured Values to Current Value."

[[LWM2M.Object.Resources.Item]]
Name = "Current Calibration"
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = ""
Units = ""
Description = "Read or Write the current calibration coefficient."

[[LWM2M.Object.Resources.Item]]
Name = "Application Type"
Operations = "RW"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "The application type of the sensor or actuator as a string depending on the use case."

[[LWM2M.Object.Resources.Item]]
Name = "Timestamp"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Time"
RangeEnumeration = ""
Units = ""
Description = "The timestamp of when the measurement was performed."

[[LWM2M.Object.Resources.Item]]
Name = "Fractional Timestamp"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Float"
RangeEnumeration = "0..1"
Units = "s"
Description = "Fractional part of the timestamp when sub-second precision is used (e.g., 0.23 for 230 ms)."

[[LWM2M.Object.Resources.Item]]
Name = "Measurement Quality Indicator"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = "0..23"
Units = ""
Description = "Measurement quality indicator reported by a smart sensor. 0: UNCHECKED No quality checks were done because they do not exist or can not be applied. 1: REJECTED WITH CERTAINTY The measured value is invalid. 2: REJECTED WITH PROBABILITY The measured value is likely invalid. 3: ACCEPTED BUT SUSPICIOUS The measured value is likely OK. 4: ACCEPTED The measured value is OK. 5-15: Reserved for future extensions. 16-23: Vendor specific measurement quality."

[[LWM2M.Object.Resources.Item]]
Name = "Measurement Quality Level"
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "Integer"
RangeEnumeration = "0..100"
Units = ""
Description = "Measurement quality level reported by a smart sensor. Quality level 100 means that the measurement has fully passed quality check algorithms. Smaller quality levels mean that quality has decreased and the measurement has only partially passed quality check algorithms. The smaller the quality level, the more caution should be used by the application when using the measurement. When the quality level is 0 it means that the measurement should certainly be rejected."
