[LWM2M.Object]
Name = "Device"
Description1 = "This IPSO object should be used to report module details."
ObjectID = 34567
ObjectURN = "urn:oma:lwm2m:x:34567"
LWM2MVersion = 1
ObjectVersion = "1"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Description2 = ""

[[LWM2M.Object.Resources.Item]]
Name = "UUID"
ResourceID = 0
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Serial ID of the Device."

[[LWM2M.Object.Resources.Item]]
Name = "Name"
ResourceID = 1
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Name of the Device."

[[LWM2M.Object.Resources.Item]]
Name = "Class"
ResourceID = 2
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "Class of the Device."

[[LWM2M.Object.Resources.Item]]
Name = "Skew"
ResourceID = 3
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Skew of the Device."

[[LWM2M.Object.Resources.Item]]
Name = "OEM Name"
ResourceID = 4
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "OEM of the Device"

[[LWM2M.Object.Resources.Item]]
Name = "Assembly Date"
ResourceID = 5
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Assembly Date of the Device."

[[LWM2M.Object.Resources.Item]]
Name = "MAC"
ResourceID = 6
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Optional"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "MAC Address for Device."

[[LWM2M.Object.Resources.Item]]
Name = "Software Version"
ResourceID = 7
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Software Version of the Device."

[[LWM2M.Object.Resources.Item]]
Name = "Production Software Version"
ResourceID = 8
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "String"
RangeEnumeration = ""
Units = ""
Description = "Production Software Version agaist which Device was tested."

[[LWM2M.Object.Resources.Item]]
Name = "Module Count"
ResourceID = 9
Operations = "R"
MultipleInstances = "Single"
Mandatory = "Mandatory"
Type = "Integer"
RangeEnumeration = ""
Units = ""
Description = "Module attached to the device."
