version: '3.3'
services:
 postgresd-registry:
  image: postgres:13.3
  ports:
   - '5305:5432'
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=Pass2020!
  networks:
   - nuru-net
  volumes:
   - postgress-data:/var/lib/postgresql

 member:
  image: registry-member
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-registry
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGID=${ORGID}
   - ORGNAME=${ORGNAME}
   - OWNERID=${OWNERID}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-registry:9095
   - MEMBER_SERVICE_HOST=member
   - MEMBER_SERVICE_PORT=9090
   - MASTERORGNAME=${MASTER_ORG_NAME}
   - PUSHGATEWAY=http://${LOCAL_HOST_IP}:9099
   - ORGREGISTRYHOST=http://${LOCAL_HOST_IP}:8060
  restart: always
  networks:
   - nuru-net
  depends_on:
   - msgclient-registry

 network:
  image: registry-network
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-registry
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-registry:9095
   - NETWORK_SERVICE_HOST=network
   - NETWORK_SERVICE_PORT=9090
   - PUSHGATEWAY=http://${LOCAL_HOST_IP}:9099
   - ORGHOST=http://${LOCAL_HOST_IP}:8060
   - COUNTRY=COD
   - CURRENCY=USD
   - LANGUAGE=en
  restart: always
  networks:
   - nuru-net
  depends_on:
   - msgclient-registry

 node:
  image: registry-node
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-registry
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGID=${ORGID}
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-registry:9095
   - NODE_SERVICE_HOST=node
   - NODE_SERVICE_PORT=9090
   - PUSHGATEWAYHOST=${LOCAL_HOST_IP}:9091
  restart: always
  networks:
   - nuru-net
  depends_on:
   - msgclient-registry

 invitation:
  image: registry-invitation
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-registry
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGID=${ORGID}
   - ORGNAME=${ORGNAME}
   - OWNERID=${OWNERID}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-registry:9095
   - INVITATION_SERVICE_HOST=invitation
   - INVITATION_SERVICE_PORT=9090
   - PUSHGATEWAY=http://${LOCAL_HOST_IP}:9099
   - ORGREGISTRYHOST=http://${LOCAL_HOST_IP}:8060
   - NOTIFICATIONHOST=http://${LOCAL_HOST_IP}:8058
   - AUTHLOGINBASEURL=http://localhost:4455/auth/login
   - INVITATIONEXPIRYTIME=72
  restart: always
  networks:
   - nuru-net
  depends_on:
   - msgclient-registry

 site:
  image: registry-site
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-registry
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - ORGNAME=${ORGNAME}
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - MSGCLIENT_HOST=msgclient-registry:9095
   - SITE_SERVICE_HOST=site
   - SITE_SERVICE_PORT=9090
   - PUSHGATEWAY=http://${LOCAL_HOST_IP}:9099
   - NETWORK=network:9090
  restart: always
  networks:
   - nuru-net
  depends_on:
   - msgclient-registry

 api-gateway-registry:
  image: registry-api-gateway-registry
  restart: always
  ports:
   - '8101:8080'
  networks:
   - nuru-net
  environment:
   - DEBUGMODE=true
   - BYPASS_AUTH_MODE=true
   # - CORS_ALLOWALLORIGINS=true
   # - CORS_ALLOWORIGINS=""
  depends_on:
   - member
   - node
   - network
   - invitation
   - postgresd-registry
   - site

 msgclient-registry:
  image: registry-msgclient-registry
  environment:
   - DEBUGMODE=true
   - DB_HOST=postgresd-registry
   - DB_PASSWORD=Pass2020!
   - DB_USER=postgres
   - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
   - SYSTEM=registry
  restart: always
  networks:
   - nuru-net
  depends_on:
   - postgresd-registry

 initclient-registry:
  # build:
  #  dockerfile: ./Dockerfile
  #  context: ../services/initClient
  image: salman-init
  environment:
   - ENV_SYSTEM_ORG=${ORGNAME}
   - ENV_DNS_REFRESH_TIME_PERIOD=30
   - ENV_SYSTEM_NAME=registry
   - ENV_SYSTEM_DNS=api-gateway-registry
   - ENV_DNS_SERVER=false
   - ENV_SYSTEM_PORT=8080
   - ENV_SYSTEM_CERT=This-is-a-certificate
   - ENV_INIT_SYSTEM_ADDR=${LOCAL_HOST_IP}
   - ENV_INIT_SYSTEM_PORT=8071
   - ENV_INIT_CLIENT_ADDR=initclient-registry
   - ENV_INIT_CLIENT_PORT=8080
   - ENV_INIT_CLIENT_TEMP_FILE=/tmp/tmpfile
  restart: always
  networks:
   - nuru-net

networks:
 nuru-net:
  external: true
  name: services_dev-net

volumes:
 postgress-data:
