// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/node/state/pkg/db"

	uuid "github.com/ukama/ukama/systems/common/uuid"
)

// NodeStateRepo is an autogenerated mock type for the NodeStateRepo type
type NodeStateRepo struct {
	mock.Mock
}

// AddNodeState provides a mock function with given fields: newState, previousState
func (_m *NodeStateRepo) AddNodeState(newState *db.NodeState, previousState *db.NodeState) error {
	ret := _m.Called(newState, previousState)

	var r0 error
	if rf, ok := ret.Get(0).(func(*db.NodeState, *db.NodeState) error); ok {
		r0 = rf(newState, previousState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLatestNodeState provides a mock function with given fields: nodeId
func (_m *NodeStateRepo) GetLatestNodeState(nodeId string) (*db.NodeState, error) {
	ret := _m.Called(nodeId)

	var r0 *db.NodeState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NodeState, error)); ok {
		return rf(nodeId)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NodeState); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NodeState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodeStateById provides a mock function with given fields: id
func (_m *NodeStateRepo) GetNodeStateById(id uuid.UUID) (*db.NodeState, error) {
	ret := _m.Called(id)

	var r0 *db.NodeState
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*db.NodeState, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *db.NodeState); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NodeState)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodeStateHistory provides a mock function with given fields: nodeId
func (_m *NodeStateRepo) GetNodeStateHistory(nodeId string) ([]db.NodeState, error) {
	ret := _m.Called(nodeId)

	var r0 []db.NodeState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]db.NodeState, error)); ok {
		return rf(nodeId)
	}
	if rf, ok := ret.Get(0).(func(string) []db.NodeState); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NodeState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodeStatesByNodeId provides a mock function with given fields: nodeId
func (_m *NodeStateRepo) GetNodeStatesByNodeId(nodeId string) ([]db.NodeState, error) {
	ret := _m.Called(nodeId)

	var r0 []db.NodeState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]db.NodeState, error)); ok {
		return rf(nodeId)
	}
	if rf, ok := ret.Get(0).(func(string) []db.NodeState); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NodeState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNodeStateRepo creates a new instance of NodeStateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeStateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeStateRepo {
	mock := &NodeStateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
