// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	semver "github.com/Masterminds/semver/v3"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Read provides a mock function with given fields: ctx, fname, aType, fversion, fext, fstore, wp
func (_m *Store) Read(ctx context.Context, fname string, aType string, fversion *semver.Version, fext string, fstore string, wp string) error {
	ret := _m.Called(ctx, fname, aType, fversion, fext, fstore, wp)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *semver.Version, string, string, string) error); ok {
		r0 = rf(ctx, fname, aType, fversion, fext, fstore, wp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
