version: "3.2"
services:
  postgresd:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ThisIsUkamaXPass
    networks:
      - ukama-net
    volumes:
      - postgress-data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - ukama-net

  rabbitmq:
    # Web interface: http://localhost:15672
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        #- ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - ukama-net
  
  
  

  # coredns:
  #   image: coredns/coredns:latest
  #   command: -conf /etc/coredns/Corefile -dns.port 53
  #   container_name: coredns
  #   restart: on-failure
  #   expose:
  #     - '53'
  #     - '53/udp'
  #   ports:
  #     - '53:53'
  #     - '53:53/udp'
  #   volumes:
  #     - './net/DEBUG/Corefile:/etc/coredns/Corefile'
  #   networks:
  #     - ukama-net
  

  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - ukama-net  

networks:
  ukama-net:
      ipam:
        driver: default
        config:
            - subnet: 10.10.0.0/24

volumes:
  postgress-data:
  rabbitmq-data:
