@startuml
skinparam BoxPadding 10
skinparam roundcorner 10
skinparam Shadowing false
skinparam monochrome true
skinparam ParticipantPadding 60
skinparam ActorBorderColor  Black
skinparam sequenceMessageAlign center
skinparam SequenceBoxBackgroundColor AliceBlue

actor User #Black

User -> Console: (/nodes)
Console -> BFF: (query getNodeStatus)
BFF -> "Auth Registery": Validate session
BFF <-- "Auth Registery": Validate Failed
Console <-- BFF: Session Validation Failed
BFF <-- "Auth Registery": Validate success
BFF --> "Metrics Registery": (GET /nodes/{{NODE_ID}}/metrics/{{METRIC_KEY}}/latest)
BFF <-- "Metrics Registery": (GET /nodes/{{NODE_ID}}/metrics/{{METRIC_KEY}}/latest response)
BFF --> Console:  (query getNodeStatus response)

@enduml