// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Network is an autogenerated mock type for the Network type
type Network struct {
	mock.Mock
}

// ValidateNetwork provides a mock function with given fields: networkId, orgId
func (_m *Network) ValidateNetwork(networkId string, orgId string) error {
	ret := _m.Called(networkId, orgId)

	if len(ret) == 0 {
		panic("no return value specified for ValidateNetwork")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(networkId, orgId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNetwork creates a new instance of Network. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetwork(t interface {
	mock.TestingT
	Cleanup(func())
}) *Network {
	mock := &Network{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
