/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2023-present, Ukama Inc.
 */
import { NOTIFICATION_SCOPE, ROLE_TYPE } from "../enums";

// mapping for role to scope
export const RoleToNotificationScopes: {
  [key in ROLE_TYPE]: Array<NOTIFICATION_SCOPE>;
} = {
  [ROLE_TYPE.ROLE_OWNER]: [
    NOTIFICATION_SCOPE.SCOPE_OWNER,
    NOTIFICATION_SCOPE.SCOPE_ORG,
    NOTIFICATION_SCOPE.SCOPE_NETWORK,
    NOTIFICATION_SCOPE.SCOPE_NETWORKS,
    NOTIFICATION_SCOPE.SCOPE_SITES,
    NOTIFICATION_SCOPE.SCOPE_SITE,
    NOTIFICATION_SCOPE.SCOPE_SUBSCRIBERS,
    NOTIFICATION_SCOPE.SCOPE_SUBSCRIBER,
    NOTIFICATION_SCOPE.SCOPE_USERS,
    NOTIFICATION_SCOPE.SCOPE_USER,
    NOTIFICATION_SCOPE.SCOPE_NODE,
  ],
  [ROLE_TYPE.ROLE_ADMIN]: [
    NOTIFICATION_SCOPE.SCOPE_NETWORK,
    NOTIFICATION_SCOPE.SCOPE_NETWORKS,
    NOTIFICATION_SCOPE.SCOPE_SITES,
    NOTIFICATION_SCOPE.SCOPE_SITE,
    NOTIFICATION_SCOPE.SCOPE_SUBSCRIBERS,
    NOTIFICATION_SCOPE.SCOPE_SUBSCRIBER,
    NOTIFICATION_SCOPE.SCOPE_USERS,
    NOTIFICATION_SCOPE.SCOPE_USER,
    NOTIFICATION_SCOPE.SCOPE_NODE,
  ],
  [ROLE_TYPE.ROLE_NETWORK_OWNER]: [
    NOTIFICATION_SCOPE.SCOPE_NETWORK,
    NOTIFICATION_SCOPE.SCOPE_SITES,
    NOTIFICATION_SCOPE.SCOPE_SITE,
    NOTIFICATION_SCOPE.SCOPE_SUBSCRIBERS,
    NOTIFICATION_SCOPE.SCOPE_SUBSCRIBER,
    NOTIFICATION_SCOPE.SCOPE_USERS,
    NOTIFICATION_SCOPE.SCOPE_USER,
    NOTIFICATION_SCOPE.SCOPE_NODE,
  ],
  [ROLE_TYPE.ROLE_VENDOR]: [NOTIFICATION_SCOPE.SCOPE_NETWORK],
  [ROLE_TYPE.ROLE_USER]: [NOTIFICATION_SCOPE.SCOPE_USER],
  [ROLE_TYPE.ROLE_INVALID]: [],
};
