// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: events.proto

#include "events.pb.h"
#include "events.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace events {

static const char* EventListener_method_names[] = {
  "/events.EventListener/SystemRegistrationEvent",
};

std::unique_ptr< EventListener::Stub> EventListener::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EventListener::Stub> stub(new EventListener::Stub(channel, options));
  return stub;
}

EventListener::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SystemRegistrationEvent_(EventListener_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status EventListener::Stub::SystemRegistrationEvent(::grpc::ClientContext* context, const ::events::RegistrationRequest& request, ::events::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::events::RegistrationRequest, ::events::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SystemRegistrationEvent_, context, request, response);
}

void EventListener::Stub::async::SystemRegistrationEvent(::grpc::ClientContext* context, const ::events::RegistrationRequest* request, ::events::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::events::RegistrationRequest, ::events::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemRegistrationEvent_, context, request, response, std::move(f));
}

void EventListener::Stub::async::SystemRegistrationEvent(::grpc::ClientContext* context, const ::events::RegistrationRequest* request, ::events::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemRegistrationEvent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::events::Response>* EventListener::Stub::PrepareAsyncSystemRegistrationEventRaw(::grpc::ClientContext* context, const ::events::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::events::Response, ::events::RegistrationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SystemRegistrationEvent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::events::Response>* EventListener::Stub::AsyncSystemRegistrationEventRaw(::grpc::ClientContext* context, const ::events::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSystemRegistrationEventRaw(context, request, cq);
  result->StartCall();
  return result;
}

EventListener::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EventListener_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EventListener::Service, ::events::RegistrationRequest, ::events::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EventListener::Service* service,
             ::grpc::ServerContext* ctx,
             const ::events::RegistrationRequest* req,
             ::events::Response* resp) {
               return service->SystemRegistrationEvent(ctx, req, resp);
             }, this)));
}

EventListener::Service::~Service() {
}

::grpc::Status EventListener::Service::SystemRegistrationEvent(::grpc::ServerContext* context, const ::events::RegistrationRequest* request, ::events::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace events

