refresh_interval_sec = 5
request_timeout_ms = 2000
stale_grace_sec = 15

[[source]]
name = "com"
url = "http://127.0.0.1:18007/metrics"
required = true

[[source]]
name = "trx"
url = "http://127.0.0.10:18007/metrics"
required = true
