
#
# Config file to build node.d for the Ukama's Virtual Node.
#

# Base image to use to build container. Examples are alpine, Ubuntu, etc.
[build-from]
	base="alpine"
	version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/distro/system/noded"
	cmd="make"
	bin_from="/distro/system/noded/build/noded"
	bin_to="/sbin/"

# for [program:<exec>] in supervisor.conf
[capp-exec]
	name="noded"
	version="latest"
	autostart="false"
	autorestart="false"
	startretries=5
	bin="noded"
	path="/sbin" # path where the exec should be. Matches build.bin_to
	args="--p /mfgdata/property/property.json --i /tmp/sys/inventory_db"
	group="on-boot"

# Nothing to see here. Move on
