#!/bin/sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2026-present, Ukama Inc.

set -u

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "usage: $0 <run-dir> [out-dir-name]" >&2
    exit 2
fi

RUN_DIR="$1"
OUT_NAME="${2:-cdr-diagnostics}"

case "$OUT_NAME" in
    ""|*/*|*..*|*[!A-Za-z0-9_.-]*)
        echo "invalid diagnostics out-dir-name: $OUT_NAME" >&2
        exit 2
        ;;
esac

OUT_DIR="$RUN_DIR/$OUT_NAME"
SUMMARY="$OUT_DIR/summary.txt"
STRICT="${ULAB_CDR_DIAG_STRICT:-0}"
NODE_GW_URL="${ULAB_UKAMA_AGENT_NODE_GW_URL:-http://localhost:8072}"
API_GW_URL="${ULAB_UKAMA_AGENT_API_GW_URL:-http://localhost:8073}"
END_TIME="$(date +%s)"
FAILURES=0

mkdir -p "$OUT_DIR"
: > "$SUMMARY"

log() {
    printf "%s\n" "$*" | tee -a "$SUMMARY"
}

warn() {
    FAILURES=$((FAILURES + 1))
    printf "WARN %s\n" "$*" | tee -a "$SUMMARY" >&2
}

safe_name() {
    printf "%s" "$1" | tr -c 'A-Za-z0-9_.-' '-'
}

json_escape() {
    # Good enough for URL/status summary labels generated by the lab.
    printf "%s" "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

write_manifest() {
    manifest="$OUT_DIR/manifest.json"
    tmp="$manifest.tmp"

    {
        printf '{\n'
        printf '  "run_dir": "%s",\n' "$(json_escape "$RUN_DIR")"
        printf '  "diagnostics_dir": "%s",\n' "$(json_escape "$OUT_NAME")"
        printf '  "node_gateway_url": "%s",\n' "$(json_escape "$NODE_GW_URL")"
        printf '  "api_gateway_url": "%s",\n' "$(json_escape "$API_GW_URL")"
        printf '  "end_time": %s\n' "$END_TIME"
        printf '}\n'
    } > "$tmp"
    mv "$tmp" "$manifest"
}

host_get() {
    label="$1"
    url="$2"
    out="$3"
    tmp="$out.tmp"
    code_file="$out.code"
    err_file="$out.err"
    code="000"

    log "HOST GET $label $url"
    code="$(curl -sS --max-time 10 -o "$tmp" -w '%{http_code}' "$url" 2>"$err_file" || true)"
    mv "$tmp" "$out" 2>/dev/null || : > "$out"
    printf "%s\n" "$code" > "$code_file"
    log "HOST GET $label status=$code out=$out"

    case "$code" in
        200|201|202|204|404) return 0 ;;
        *) warn "host query failed label=$label status=$code url=$url"; return 1 ;;
    esac
}

container_get() {
    container="$1"
    label="$2"
    url="$3"
    out="$4"
    tmp="$out.tmp"
    code_file="$out.code"
    err_file="$out.err"
    code="000"

    log "TOWER GET $container $label $url"

    if ! podman inspect -f '{{.State.Running}}' "$container" 2>/dev/null | grep -q '^true$'; then
        warn "container not running for tower query: $container"
        : > "$out"
        printf "000\n" > "$code_file"
        return 1
    fi

    code="$(podman exec "$container" sh -lc \
        "curl -sS --max-time 10 -o /tmp/ulab-cdr-diag.out -w '%{http_code}' '$url'" \
        2>"$err_file" || true)"
    podman exec "$container" sh -lc \
        'cat /tmp/ulab-cdr-diag.out 2>/dev/null; rm -f /tmp/ulab-cdr-diag.out' \
        > "$tmp" 2>/dev/null || true
    mv "$tmp" "$out" 2>/dev/null || : > "$out"
    printf "%s\n" "$code" > "$code_file"
    log "TOWER GET $container $label status=$code out=$out"

    case "$code" in
        200|201|202|204|404) return 0 ;;
        *) warn "tower query failed container=$container label=$label status=$code url=$url"; return 1 ;;
    esac
}

collect_tower_ukama() {
    container="$1"
    out="$2"
    err="$out.err"

    log "TOWER TAR $container /ukama -> $out"

    if ! podman inspect -f '{{.State.Running}}' "$container" 2>/dev/null | grep -q '^true$'; then
        warn "container not running for /ukama collection: $container"
        return 1
    fi

    if podman exec "$container" sh -lc \
        'if [ -d /ukama ]; then cd / && tar -czf - ukama; else echo /ukama missing >&2; exit 3; fi' \
        > "$out" 2>"$err"; then
        log "TOWER TAR ok $out"
        return 0
    fi

    warn "failed to collect /ukama from $container"
    return 1
}

ue_matches_site() {
    ue_file="$1"
    site_ref="$2"

    UE_SITE_REF=""
    # shellcheck disable=SC1090
    . "$ue_file"

    if [ -z "$site_ref" ] || [ -z "${SITE_REF:-}" ]; then
        return 0
    fi

    [ "${SITE_REF:-}" = "$site_ref" ]
}

collect_ue_queries() {
    ue_file="$1"
    tower_container="$2"
    tower_dir="$3"
    tnode_id="$4"

    IMSI=""
    ICCID=""
    UE_ID=""
    UE_REF=""
    SITE_REF=""
    # shellcheck disable=SC1090
    . "$ue_file"

    if [ -z "${IMSI:-}" ]; then
        warn "skip UE state without IMSI: $ue_file"
        return 0
    fi

    ue_key="${UE_ID:-${UE_REF:-$IMSI}}"
    ue_safe="$(safe_name "$ue_key")"
    ue_dir="$tower_dir/ue-$ue_safe"
    mkdir -p "$ue_dir"

    {
        echo "UE_FILE=$ue_file"
        echo "UE_ID=${UE_ID:-}"
        echo "UE_REF=${UE_REF:-}"
        echo "IMSI=${IMSI:-}"
        echo "ICCID=${ICCID:-}"
        echo "SITE_REF=${SITE_REF:-}"
        echo "TNODE_ID=${tnode_id:-}"
        echo "TOWER_CONTAINER=$tower_container"
    } > "$ue_dir/ue.env"

    container_get "$tower_container" "epcemu-status" \
        "http://127.0.0.1:18028/v1/status" \
        "$ue_dir/tower-epcemu-status.json" || true
    container_get "$tower_container" "pcrf-status" \
        "http://127.0.0.1:18030/v1/status" \
        "$ue_dir/tower-pcrf-status.json" || true
    container_get "$tower_container" "pcrf-service" \
        "http://127.0.0.1:18030/v1/service" \
        "$ue_dir/tower-pcrf-service.json" || true
    container_get "$tower_container" "pcrf-cdr-imsi-$IMSI" \
        "http://127.0.0.1:18030/v1/cdr/imsi/$IMSI" \
        "$ue_dir/tower-pcrf-cdr.json" || true

    host_get "node-gw-cdr-imsi-$IMSI" \
        "$NODE_GW_URL/v1/cdr/$IMSI?start_time=0&end_time=$END_TIME" \
        "$ue_dir/agent-node-gw-cdr.json" || true
    host_get "node-gw-asr-usage-imsi-$IMSI" \
        "$NODE_GW_URL/v1/asr/$IMSI/usage" \
        "$ue_dir/agent-node-gw-asr-usage.json" || true

    if [ -n "${ICCID:-}" ]; then
        host_get "api-gw-asr-usage-iccid-$ICCID" \
            "$API_GW_URL/v1/asr/$ICCID/usage" \
            "$ue_dir/agent-api-gw-asr-usage.json" || true
        host_get "api-gw-asr-period-iccid-$ICCID" \
            "$API_GW_URL/v1/asr/$ICCID/period?start_time=0&end_time=$END_TIME" \
            "$ue_dir/agent-api-gw-asr-period.json" || true
        host_get "api-gw-query-usage-iccid-$ICCID" \
            "$API_GW_URL/v1/usage/$ICCID?node_id=$tnode_id&session=0&from=0&to=$END_TIME&count=0&sort=true" \
            "$ue_dir/agent-api-gw-query-usage.json" || true
    fi
}

collect_tower() {
    node_file="$1"

    LOGICAL_NODE_ID=""
    FACTORY_NODE_ID=""
    NODE_KIND=""
    NODE_TYPE=""
    SITE_REF=""
    CONTAINER_NAME=""
    # shellcheck disable=SC1090
    . "$node_file"

    kind="${NODE_KIND:-${NODE_TYPE:-}}"
    if [ "$kind" != "tnode" ]; then
        return 0
    fi

    if [ -z "${CONTAINER_NAME:-}" ]; then
        warn "tower node state missing CONTAINER_NAME: $node_file"
        return 0
    fi

    tower_key="${LOGICAL_NODE_ID:-${FACTORY_NODE_ID:-$CONTAINER_NAME}}"
    tower_safe="$(safe_name "$tower_key")"
    tower_dir="$OUT_DIR/$tower_safe"
    mkdir -p "$tower_dir"

    {
        echo "NODE_FILE=$node_file"
        echo "LOGICAL_NODE_ID=${LOGICAL_NODE_ID:-}"
        echo "FACTORY_NODE_ID=${FACTORY_NODE_ID:-}"
        echo "NODE_KIND=$kind"
        echo "SITE_REF=${SITE_REF:-}"
        echo "CONTAINER_NAME=$CONTAINER_NAME"
    } > "$tower_dir/tower.env"

    collect_tower_ukama "$CONTAINER_NAME" "$tower_dir/ukama.tgz" || true

    if [ -d "$RUN_DIR/runtime-ues" ]; then
        found=0
        for ue_file in "$RUN_DIR"/runtime-ues/*.env; do
            [ -f "$ue_file" ] || continue
            if ue_matches_site "$ue_file" "${SITE_REF:-}"; then
                found=$((found + 1))
                collect_ue_queries "$ue_file" "$CONTAINER_NAME" "$tower_dir" \
                    "${FACTORY_NODE_ID:-${LOGICAL_NODE_ID:-}}"
            fi
        done
        if [ "$found" -eq 0 ]; then
            log "no UE state matched tower=$tower_key site=${SITE_REF:-}"
        fi
    else
        log "no runtime-ues directory found"
    fi
}

write_manifest
log "diagnostics begin run_dir=$RUN_DIR out=$OUT_DIR"
log "node_gw=$NODE_GW_URL api_gw=$API_GW_URL end_time=$END_TIME"

if [ ! -d "$RUN_DIR/runtime-nodes" ]; then
    warn "runtime-nodes directory not found: $RUN_DIR/runtime-nodes"
else
    for node_file in "$RUN_DIR"/runtime-nodes/*.env; do
        [ -f "$node_file" ] || continue
        collect_tower "$node_file"
    done
fi

log "diagnostics complete failures=$FAILURES out=$OUT_DIR"

if [ "$STRICT" = "1" ] && [ "$FAILURES" -gt 0 ]; then
    exit 1
fi

exit 0
