#!/bin/sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2026-present, Ukama Inc.

set -eu

if [ "$#" -lt 2 ]; then
    echo "usage: $0 <logical-node-id> <run-dir>" >&2
    exit 2
fi

LOGICAL_NODE_ID="$1"
RUN_DIR="$2"

STATE_DIR="$RUN_DIR/runtime-nodes"
TIMEOUT_SEC="${ULAB_NODE_READY_TIMEOUT_SEC:-180}"
SLEEP_SEC="${ULAB_NODE_READY_SLEEP_SEC:-3}"
STARTER_PORT="${ULAB_STARTER_PORT:-18001}"

safe_name() {
    printf "%s" "$1" | tr -c 'A-Za-z0-9_.-' '-'
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "missing required command: $1" >&2
        exit 1
    }
}

load_state() {
    state_file="$STATE_DIR/$(safe_name "$LOGICAL_NODE_ID").env"

    if [ ! -f "$state_file" ]; then
        echo "node state not found for $LOGICAL_NODE_ID: $state_file" >&2
        exit 1
    fi

    # State file is generated by build-and-start-site.sh/runtime.c and contains
    # simple KEY=value lines.
    # shellcheck disable=SC1090
    . "$state_file"
}

node_kind() {
    kind="${NODE_KIND:-}"

    if [ -n "$kind" ]; then
        echo "$kind"
        return
    fi

    case "${FACTORY_NODE_ID:-} ${LOGICAL_NODE_ID:-}" in
        *tnode*|*tower*) echo "tnode" ;;
        *anode*|*amplifier*) echo "anode" ;;
        *cnode*|*controller*) echo "cnode" ;;
        *) echo "node" ;;
    esac
}

required_apps() {
    if [ -n "${ULAB_REQUIRED_STARTER_APPS:-}" ]; then
        echo "$ULAB_REQUIRED_STARTER_APPS"
        return
    fi

    case "$(node_kind)" in
        tnode|tower)
            echo "${ULAB_TOWER_READY_APPS:-init-network,noded,meshd,epcemu,pcrf}"
            ;;
        anode|amplifier)
            echo "${ULAB_AMPLIFIER_READY_APPS:-noded,meshd}"
            ;;
        cnode|controller)
            echo "${ULAB_CONTROLLER_READY_APPS:-noded,meshd}"
            ;;
        *)
            echo "${ULAB_NODE_READY_APPS:-noded,meshd}"
            ;;
    esac
}

container_running() {
    podman inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null |
        grep -q '^true$'
}

container_logs_tail() {
    podman logs --tail 80 "$CONTAINER_NAME" 2>/dev/null || true
}

starter_status() {
    podman exec "$CONTAINER_NAME" sh -lc \
        "curl -fsS --max-time 2 http://127.0.0.1:${STARTER_PORT}/v1/status" \
        2>/dev/null
}

check_required_apps() {
    tmp_file="/tmp/ukama-starter-status.$$"
    apps="$(required_apps)"

    if ! starter_status > "$tmp_file"; then
        rm -f "$tmp_file"
        return 1
    fi

    REQUIRED_APPS="$apps" python3 - "$tmp_file" <<'PY'
import json
import os
import sys

path = sys.argv[1]
required = [x.strip() for x in os.environ.get("REQUIRED_APPS", "").split(",") if x.strip()]

try:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
except Exception as exc:
    print(f"invalid starter.d JSON: {exc}", file=sys.stderr)
    sys.exit(1)

starterd = data.get("starterd") or {}
if starterd.get("updateInProgress") is True:
    print("starterd update in progress", file=sys.stderr)
    sys.exit(1)

if starterd.get("terminateRequested") is True:
    print("starterd terminate requested", file=sys.stderr)
    sys.exit(1)

apps = {}
for space in data.get("spaces") or []:
    for app in space.get("apps") or []:
        name = str(app.get("name") or "")
        state = str(app.get("state") or "").lower()
        if name:
            apps[name] = state

bad = []

for name in required:
    state = apps.get(name)
    if state is None:
        bad.append(f"{name}: missing")
    elif state not in ("running", "active"):
        bad.append(f"{name}: {state}")

if bad:
    for item in bad:
        print(item, file=sys.stderr)
    sys.exit(1)

sys.exit(0)
PY

    rc="$?"
    rm -f "$tmp_file"
    return "$rc"
}

print_debug() {
    echo "---- podman ps ----" >&2
    podman ps -a --filter "name=$CONTAINER_NAME" >&2 || true

    echo "---- required starter.d apps ----" >&2
    echo "$(required_apps)" >&2

    echo "---- starter.d /v1/status ----" >&2
    starter_status >&2 || echo "starter.d not reachable on port ${STARTER_PORT}" >&2

    echo "---- container logs ----" >&2
    container_logs_tail >&2
}

node_ready() {
    container_running || return 1
    check_required_apps || return 1
    return 0
}

need_cmd podman
need_cmd python3
load_state

echo "wait-node: logical=$LOGICAL_NODE_ID factory=${FACTORY_NODE_ID:-} container=$CONTAINER_NAME kind=$(node_kind) apps=$(required_apps) timeout=${TIMEOUT_SEC}s"

start_ts="$(date +%s)"

while :; do
    if node_ready; then
        echo "node-ready logical=$LOGICAL_NODE_ID factory=${FACTORY_NODE_ID:-} container=$CONTAINER_NAME"
        exit 0
    fi

    now_ts="$(date +%s)"
    elapsed=$((now_ts - start_ts))

    if [ "$elapsed" -ge "$TIMEOUT_SEC" ]; then
        echo "node not ready after ${TIMEOUT_SEC}s: logical=$LOGICAL_NODE_ID factory=${FACTORY_NODE_ID:-} container=$CONTAINER_NAME" >&2
        print_debug
        exit 1
    fi

    sleep "$SLEEP_SEC"
done
