#!/bin/sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2026-present, Ukama Inc.

set -eu

if [ "$#" -lt 2 ]; then
    echo "usage: $0 <logical-node-id> <run-dir>" >&2
    exit 2
fi

LOGICAL_NODE_ID="$1"
RUN_DIR="$2"

STATE_DIR="$RUN_DIR/runtime-nodes"
TIMEOUT_SEC="${ULAB_NODE_READY_TIMEOUT_SEC:-180}"
SLEEP_SEC="${ULAB_NODE_READY_SLEEP_SEC:-3}"

safe_name() {
    echo "$1" | tr -c 'A-Za-z0-9_.-' '-'
}

need_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "missing required command: $1" >&2
        exit 1
    fi
}

load_state() {
    state_file="$STATE_DIR/$(safe_name "$LOGICAL_NODE_ID").env"

    if [ ! -f "$state_file" ]; then
        echo "node state not found for $LOGICAL_NODE_ID: $state_file" >&2
        exit 1
    fi

    # State file is generated by start-node.sh and contains simple KEY=value lines.
    # shellcheck disable=SC1090
    . "$state_file"
}

container_running() {
    podman inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q '^true$'
}

container_logs_tail() {
    podman logs --tail 80 "$CONTAINER_NAME" 2>/dev/null || true
}

http_ready() {
    port="$1"
    path="$2"

    podman exec "$CONTAINER_NAME" sh -lc \
        "curl -fsS --max-time 2 http://127.0.0.1:$port$path" \
        >/tmp/ukama-node-ready.$$ 2>/dev/null || return 1

    if grep -q '"ready"[[:space:]]*:[[:space:]]*true' /tmp/ukama-node-ready.$$; then
        rm -f /tmp/ukama-node-ready.$$
        return 0
    fi

    if grep -q '"state"[[:space:]]*:[[:space:]]*"ready"' /tmp/ukama-node-ready.$$; then
        rm -f /tmp/ukama-node-ready.$$
        return 0
    fi

    rm -f /tmp/ukama-node-ready.$$
    return 1
}

service_reachable() {
    port="$1"
    path="$2"

    podman exec "$CONTAINER_NAME" sh -lc \
        "curl -fsS --max-time 2 http://127.0.0.1:$port$path" \
        >/dev/null 2>&1
}

node_ready() {
    container_running || return 1

    #
    # Strong readiness: known Ukama runtime services report ready.
    # Some virtual node images may not run every service for every node type,
    # so this checks the core services first and treats starter as useful-but-not-fatal.
    #
    http_ready 18026 /v1/status || return 1

    if ! service_reachable 18001 /v1/status; then
        service_reachable 18001 /v1/ping || true
    fi

    #
    # EPC/PCRF is tower-focused. If present, they must be ready.
    # If not present yet for cnode/anode images, do not block forever on them.
    #
    if service_reachable 18028 /v1/status; then
        http_ready 18028 /v1/status || return 1
    fi

    if service_reachable 18030 /v1/status; then
        http_ready 18030 /v1/status || return 1
    fi

    return 0
}

need_cmd podman
load_state

echo "wait-node: logical=$LOGICAL_NODE_ID factory=$FACTORY_NODE_ID container=$CONTAINER_NAME timeout=${TIMEOUT_SEC}s"

start_ts="$(date +%s)"

while :; do
    if node_ready; then
        echo "node-ready logical=$LOGICAL_NODE_ID factory=$FACTORY_NODE_ID container=$CONTAINER_NAME"
        exit 0
    fi

    now_ts="$(date +%s)"
    elapsed=$((now_ts - start_ts))

    if [ "$elapsed" -ge "$TIMEOUT_SEC" ]; then
        echo "node not ready after ${TIMEOUT_SEC}s: logical=$LOGICAL_NODE_ID factory=$FACTORY_NODE_ID container=$CONTAINER_NAME" >&2
        echo "---- podman ps ----" >&2
        podman ps -a --filter "name=$CONTAINER_NAME" >&2 || true
        echo "---- container logs ----" >&2
        container_logs_tail >&2
        exit 1
    fi

    sleep "$SLEEP_SEC"
done
