#!/bin/sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2026-present, Ukama Inc.

set -eu

if [ "$#" -lt 2 ]; then
    echo "usage: $0 <logical-node-id> <run-dir>" >&2
    exit 2
fi

LOGICAL_NODE_ID="$1"
RUN_DIR="$2"

STATE_DIR="$RUN_DIR/runtime-nodes"
TIMEOUT_SEC="${ULAB_NODE_READY_TIMEOUT_SEC:-180}"
SLEEP_SEC="${ULAB_NODE_READY_SLEEP_SEC:-3}"
LIFECYCLE_PORT="${ULAB_LIFECYCLE_PORT:-8097}"
STARTER_PORT="${ULAB_STARTER_PORT:-18001}"

safe_name() {
    printf "%s" "$1" | tr -c 'A-Za-z0-9_.-' '-'
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "missing required command: $1" >&2
        exit 1
    }
}

load_state() {
    state_file="$STATE_DIR/$(safe_name "$LOGICAL_NODE_ID").env"

    if [ ! -f "$state_file" ]; then
        echo "node state not found for $LOGICAL_NODE_ID: $state_file" >&2
        exit 1
    fi

    # State file is generated by build-and-start-site.sh/runtime.c and contains
    # simple KEY=value lines.
    # shellcheck disable=SC1090
    . "$state_file"
}

container_running() {
    podman inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null |
        grep -q '^true$'
}

starter_status() {
    podman exec "$CONTAINER_NAME" sh -lc \
        "curl -fsS --max-time 2 http://127.0.0.1:${STARTER_PORT}/v1/status" \
        2>/dev/null
}

lifecycle_status() {
    podman exec "$CONTAINER_NAME" sh -lc \
        "curl -fsS --max-time 2 http://127.0.0.1:${LIFECYCLE_PORT}/v1/status" \
        2>/dev/null
}

lifecycle_state() {
    lifecycle_status | python3 -c '
import json
import sys

try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(1)

state = data.get("state")
if not isinstance(state, str) or not state:
    sys.exit(1)

print(state.upper())
'
}

print_debug() {
    echo "---- podman ps ----" >&2
    podman ps -a --filter "name=$CONTAINER_NAME" >&2 || true

    echo "---- lifecycle.d /v1/status ----" >&2
    lifecycle_status >&2 ||
        echo "lifecycle.d not reachable on port ${LIFECYCLE_PORT}" >&2

    echo "---- starter.d /v1/status ----" >&2
    starter_status >&2 ||
        echo "starter.d not reachable on port ${STARTER_PORT}" >&2

    echo "---- starter.d /v1/ready ----" >&2
    podman exec "$CONTAINER_NAME" sh -lc \
        "curl -sS --max-time 2 http://127.0.0.1:${STARTER_PORT}/v1/ready" \
        >&2 2>/dev/null || true

    echo "---- container logs ----" >&2
    podman logs --tail 80 "$CONTAINER_NAME" >&2 2>/dev/null || true
}

need_cmd podman
need_cmd python3
load_state

echo "wait-node: logical=$LOGICAL_NODE_ID factory=${FACTORY_NODE_ID:-} " \
     "container=$CONTAINER_NAME timeout=${TIMEOUT_SEC}s"

start_ts="$(date +%s)"

while :; do
    state=""
    if container_running; then
        state="$(lifecycle_state 2>/dev/null || true)"
    fi

    case "$state" in
        READY|OPERATIONAL)
            echo "node-ready logical=$LOGICAL_NODE_ID " \
                 "factory=${FACTORY_NODE_ID:-} " \
                 "container=$CONTAINER_NAME lifecycle=$state"
            exit 0
            ;;

        FAULTY)
            echo "node lifecycle is FAULTY: logical=$LOGICAL_NODE_ID " \
                 "factory=${FACTORY_NODE_ID:-} " \
                 "container=$CONTAINER_NAME" >&2
            print_debug
            exit 1
            ;;
    esac

    now_ts="$(date +%s)"
    elapsed=$((now_ts - start_ts))

    if [ "$elapsed" -ge "$TIMEOUT_SEC" ]; then
        echo "node not ready after ${TIMEOUT_SEC}s: " \
             "logical=$LOGICAL_NODE_ID factory=${FACTORY_NODE_ID:-} " \
             "container=$CONTAINER_NAME lifecycle=${state:-unavailable}" \
             >&2
        print_debug
        exit 1
    fi

    sleep "$SLEEP_SEC"
done
