// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/ukama-agent/asr/pb/gen"
)

// asr is an autogenerated mock type for the asr type
type asr struct {
	mock.Mock
}

// CreateProfile provides a mock function with given fields: req
func (_m *asr) CreateProfile(req *gen.CreateProfileReq) (*gen.CreateProfileResp, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 *gen.CreateProfileResp
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.CreateProfileReq) (*gen.CreateProfileResp, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.CreateProfileReq) *gen.CreateProfileResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.CreateProfileResp)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.CreateProfileReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProfile provides a mock function with given fields: req
func (_m *asr) DeleteProfile(req *gen.DeleteProfileReq) (*gen.DeleteProfileResp, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfile")
	}

	var r0 *gen.DeleteProfileResp
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.DeleteProfileReq) (*gen.DeleteProfileResp, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.DeleteProfileReq) *gen.DeleteProfileResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DeleteProfileResp)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.DeleteProfileReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsage provides a mock function with given fields: req
func (_m *asr) GetUsage(req *gen.UsageReq) (*gen.UsageResp, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetUsage")
	}

	var r0 *gen.UsageResp
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.UsageReq) (*gen.UsageResp, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.UsageReq) *gen.UsageResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.UsageResp)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.UsageReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsageForPeriod provides a mock function with given fields: req
func (_m *asr) GetUsageForPeriod(req *gen.UsageForPeriodReq) (*gen.UsageResp, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetUsageForPeriod")
	}

	var r0 *gen.UsageResp
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.UsageForPeriodReq) (*gen.UsageResp, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.UsageForPeriodReq) *gen.UsageResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.UsageResp)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.UsageForPeriodReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryUsage provides a mock function with given fields: req
func (_m *asr) QueryUsage(req *gen.QueryUsageReq) (*gen.QueryUsageResp, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for QueryUsage")
	}

	var r0 *gen.QueryUsageResp
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.QueryUsageReq) (*gen.QueryUsageResp, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.QueryUsageReq) *gen.QueryUsageResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.QueryUsageResp)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.QueryUsageReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: req
func (_m *asr) Read(req *gen.ReadReq) (*gen.ReadResp, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *gen.ReadResp
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.ReadReq) (*gen.ReadResp, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.ReadReq) *gen.ReadResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ReadResp)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.ReadReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePackage provides a mock function with given fields: req
func (_m *asr) UpdatePackage(req *gen.UpdatePackageReq) (*gen.UpdatePackageResp, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePackage")
	}

	var r0 *gen.UpdatePackageResp
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.UpdatePackageReq) (*gen.UpdatePackageResp, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.UpdatePackageReq) *gen.UpdatePackageResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.UpdatePackageResp)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.UpdatePackageReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newAsr creates a new instance of asr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newAsr(t interface {
	mock.TestingT
	Cleanup(func())
}) *asr {
	mock := &asr{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
