// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorRepo is an autogenerated mock type for the ErrorRepo type
type ErrorRepo struct {
	mock.Mock
}

// Insert provides a mock function with given fields: orgID, kpiKey, windowID, errMsg
func (_m *ErrorRepo) Insert(orgID string, kpiKey string, windowID int64, errMsg string) error {
	ret := _m.Called(orgID, kpiKey, windowID, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64, string) error); ok {
		r0 = rf(orgID, kpiKey, windowID, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewErrorRepo creates a new instance of ErrorRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorRepo {
	mock := &ErrorRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
