// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "github.com/ukama/ukama/systems/inventory/site/pkg/db"
)

// SiteRepo is an autogenerated mock type for the SiteRepo type
type SiteRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *SiteRepo) Get() (*db.Site, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *db.Site
	var r1 error
	if rf, ok := ret.Get(0).(func() (*db.Site, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *db.Site); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Site)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSiteRepo creates a new instance of SiteRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSiteRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SiteRepo {
	mock := &SiteRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
