// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gen "github.com/ukama/ukama/systems/analytics/aggregator/pb/gen"
)

// aggregator is an autogenerated mock type for the aggregator type
type aggregator struct {
	mock.Mock
}

// GetKpiBreakdown provides a mock function with given fields: key, span, op, by, top, scope
func (_m *aggregator) GetKpiBreakdown(key string, span string, op string, by string, top int32, scope map[string]string) (*gen.GetKpiBreakdownResponse, error) {
	ret := _m.Called(key, span, op, by, top, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetKpiBreakdown")
	}

	var r0 *gen.GetKpiBreakdownResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int32, map[string]string) (*gen.GetKpiBreakdownResponse, error)); ok {
		return rf(key, span, op, by, top, scope)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, int32, map[string]string) *gen.GetKpiBreakdownResponse); ok {
		r0 = rf(key, span, op, by, top, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetKpiBreakdownResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, int32, map[string]string) error); ok {
		r1 = rf(key, span, op, by, top, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKpiTimeSeries provides a mock function with given fields: keys, span, op, from, to, scope, groupBy
func (_m *aggregator) GetKpiTimeSeries(keys []string, span string, op string, from string, to string, scope map[string]string, groupBy []string) (*gen.GetKpiTimeSeriesResponse, error) {
	ret := _m.Called(keys, span, op, from, to, scope, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetKpiTimeSeries")
	}

	var r0 *gen.GetKpiTimeSeriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, string, string, string, string, map[string]string, []string) (*gen.GetKpiTimeSeriesResponse, error)); ok {
		return rf(keys, span, op, from, to, scope, groupBy)
	}
	if rf, ok := ret.Get(0).(func([]string, string, string, string, string, map[string]string, []string) *gen.GetKpiTimeSeriesResponse); ok {
		r0 = rf(keys, span, op, from, to, scope, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetKpiTimeSeriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string, string, string, string, map[string]string, []string) error); ok {
		r1 = rf(keys, span, op, from, to, scope, groupBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKpis provides a mock function with given fields: keys, span, op, scope, groupBy
func (_m *aggregator) GetKpis(keys []string, span string, op string, scope map[string]string, groupBy []string) (*gen.GetKpisResponse, error) {
	ret := _m.Called(keys, span, op, scope, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetKpis")
	}

	var r0 *gen.GetKpisResponse
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, string, string, map[string]string, []string) (*gen.GetKpisResponse, error)); ok {
		return rf(keys, span, op, scope, groupBy)
	}
	if rf, ok := ret.Get(0).(func([]string, string, string, map[string]string, []string) *gen.GetKpisResponse); ok {
		r0 = rf(keys, span, op, scope, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetKpisResponse)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string, string, map[string]string, []string) error); ok {
		r1 = rf(keys, span, op, scope, groupBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPerformanceReport provides a mock function with given fields: report, span, scope, top
func (_m *aggregator) GetPerformanceReport(report string, span string, scope map[string]string, top int32) (*gen.GetPerformanceReportResponse, error) {
	ret := _m.Called(report, span, scope, top)

	if len(ret) == 0 {
		panic("no return value specified for GetPerformanceReport")
	}

	var r0 *gen.GetPerformanceReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]string, int32) (*gen.GetPerformanceReportResponse, error)); ok {
		return rf(report, span, scope, top)
	}
	if rf, ok := ret.Get(0).(func(string, string, map[string]string, int32) *gen.GetPerformanceReportResponse); ok {
		r0 = rf(report, span, scope, top)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetPerformanceReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, map[string]string, int32) error); ok {
		r1 = rf(report, span, scope, top)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListKpis provides a mock function with no fields
func (_m *aggregator) ListKpis() (*gen.ListKpisResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListKpis")
	}

	var r0 *gen.ListKpisResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*gen.ListKpisResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *gen.ListKpisResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ListKpisResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReports provides a mock function with no fields
func (_m *aggregator) ListReports() (*gen.ListReportsResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListReports")
	}

	var r0 *gen.ListReportsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*gen.ListReportsResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *gen.ListReportsResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ListReportsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: req
func (_m *aggregator) Query(req *gen.QueryRequest) (*gen.QueryResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *gen.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gen.QueryRequest) (*gen.QueryResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*gen.QueryRequest) *gen.QueryResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gen.QueryRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newAggregator creates a new instance of aggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newAggregator(t interface {
	mock.TestingT
	Cleanup(func())
}) *aggregator {
	mock := &aggregator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
