// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pb "github.com/ukama/ukama/systems/node/operation-monitor/pb/gen"
)

// OperationMonitor is an autogenerated mock type for the OperationMonitor type
type OperationMonitor struct {
	mock.Mock
}

func (_m *OperationMonitor) Register(req *pb.RegisterIntentRequest) (*pb.RegisterIntentResponse, error) {
	ret := _m.Called(req)

	var r0 *pb.RegisterIntentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*pb.RegisterIntentRequest) (*pb.RegisterIntentResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*pb.RegisterIntentRequest) *pb.RegisterIntentResponse); ok {
		r0 = rf(req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*pb.RegisterIntentResponse)
	}
	if rf, ok := ret.Get(1).(func(*pb.RegisterIntentRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *OperationMonitor) Close() {
	_m.Called()
}
