// Code generated by mockery v2.21.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	uuid "github.com/ukama/ukama/systems/common/uuid"
)

// OrgMemberRoleClient is an autogenerated mock type for the OrgMemberRoleClient type
type OrgMemberRoleClient struct {
	mock.Mock
}

// GetMemberRole provides a mock function with given fields: userId, orgId
func (_m *OrgMemberRoleClient) GetMemberRole(userId uuid.UUID, orgId uuid.UUID) (string, error) {
	ret := _m.Called(userId, orgId)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (string, error)); ok {
		return rf(userId, orgId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) string); ok {
		r0 = rf(userId, orgId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(userId, orgId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrgMemberRoleClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrgMemberRoleClient creates a new instance of OrgMemberRoleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrgMemberRoleClient(t mockConstructorTestingTNewOrgMemberRoleClient) *OrgMemberRoleClient {
	mock := &OrgMemberRoleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
