# THIS FILE IS GENERATED AUTOMATICALLY BY RUNNING gen-workflow.sh 
# DON'T CHANGE IT MANUALLY TO AVOID YOUR CHANGES BEING OVERWRITTEN
# USE workflow-template.yaml FOR MAKING CHANGES IN WORKFLOWS
name: build-metrics-node
on:  
  push:   
    paths:
        - "metrics/node-metrics/**"
        - ".github/workflows/metrics-node.yml"

jobs:  
  build:
    env: 
      working-directory: metrics/node

    name: build and test
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Test
      run: go test ./...
      working-directory: ${{ env.working-directory }}
    
    - name: lint
      uses: golangci/golangci-lint-action@v2
      with:            
          working-directory: ${{ env.working-directory }}