# THIS FILE IS GENERATED AUTOMATICALLY BY RUNNING gen-workflow.sh
# DON'T CHANGE IT MANUALLY TO AVOID YOUR CHANGES BEING OVERWRITTEN
# USE workflow-template.yaml FOR MAKING CHANGES IN WORKFLOWS
name: daily-systems-billing-collector
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    env:
      working-directory: systems/billing/collector

    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build app
      uses: ./.github/actions/compile-test-go
      with:
        registry-name: billing/collector
        working-directory: ${{ env.working-directory }}
        github-bot-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
        aws-secret-key: ${{ secrets.AWS_REGISTRY_SECRET_ACCESS_KEY }}
        aws-access-key: ${{ secrets.AWS_REGISTRY_ACCESS_KEY_ID }}
        build-listener: false


  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      working-directory: systems/billing/collector
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: ./.github/actions/lint-go
        with:
          working-directory: ${{ env.working-directory }}
          github-bot-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
