# THIS FILE IS GENERATED AUTOMATICALLY BY RUNNING gen-workflow.sh 
# DON'T CHANGE IT MANUALLY TO AVOID YOUR CHANGES BEING OVERWRITTEN
# USE workflow-template.yaml FOR MAKING CHANGES IN WORKFLOWS
name: build-systems-subscriber-sim-manager
on:  
  push:   
    paths:
        - "systems/subscriber/sim-manager/**"
        - ".github/workflows/systems-subscriber-sim-manager.yaml"
 
  workflow_dispatch:

jobs:  
  build:
    env: 
      working-directory: systems/subscriber/sim-manager

    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build app
      uses: ./.github/actions/build-go
      with:
        registry-name: subscriber/sim-manager
        working-directory: ${{ env.working-directory }}
        github-bot-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
        aws-secret-key: ${{ secrets.AWS_REGISTRY_SECRET_ACCESS_KEY }}
        aws-access-key: ${{ secrets.AWS_REGISTRY_ACCESS_KEY_ID }}
        build-listener: false
    
  sonar-scan:
    name: sonar-scan
    needs: build
    runs-on: ubuntu-latest
    env: 
      working-directory: systems/subscriber/sim-manager
    steps:
      - uses: actions/checkout@v3
      - name: scan
        uses: ./.github/actions/sonar-go
        with:         
          working-directory: ${{ env.working-directory }}
          github-bot-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: ukama_systems_subscriber_sim-manager

  lint:
    name: lint
    runs-on: ubuntu-latest
    env: 
      working-directory: systems/subscriber/sim-manager
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: ./.github/actions/lint-go
        with:
          working-directory: ${{ env.working-directory }}
          github-bot-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
          

  release:
      name: release
      needs: [build, lint]
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      env:
        working-directory: systems/subscriber/sim-manager
      steps:
        - uses: actions/checkout@v3
        
        - name: Init vars
          id: vars_step
          uses: ./.github/actions/git-vars

        - name: update gitops
          uses: denispalnitsky/gitops-release@v9
          with:
            filename: "releases/subscriber-helmfile.yaml"
            key: "simmanagerImageTag"
            value:  ${{ steps.vars_step.outputs.sha-short }}
            github-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
            github-org-and-repo: "ukama/infra-as-code"
            github-user-mail: "bot@ukama.com"
            github-username: "ukama-bot"
