# THIS FILE IS GENERATED AUTOMATICALLY BY RUNNING gen-workflow.sh 
# DON'T CHANGE IT MANUALLY TO AVOID YOUR CHANGES BEING OVERWRITTEN
# USE workflow-template.yaml FOR MAKING CHANGES IN WORKFLOWS
name: build-virtualNode
on:
  push:
    paths:
        - "testing/node"
        - "github/workflows/testing-node-virtualnode.yaml"
  workflow_dispatch:

jobs:
  build:
    
    name: Build virtual node
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      run: git submodule update --init --recursive    
  
    - name: Dependencies
      run:  sudo apt-get update && sudo apt-get install bc libncurses5-dev lzop libssl-dev gnat flex zlib1g-dev gcc-arm-linux-gnueabihf automake-1.15 bison libelf-dev cmake curl libtool tcl pkg-config autopoint wget libisl-dev g++ texinfo texlive ghostscript libnftnl-dev libmnl-dev patchelf -y

    - name: Install Dependencies
      working-directory: ./nodes/ukamaOS/distro/vendor
      run: |
        make tomlc jansson TARGET=linux
       
    - name: Build VirtualNodeBuilder
      working-directory: ./testing/node
      run: |
        make sourcetgz

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_REGISTRY_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_REGISTRY_SECRET_ACCESS_KEY  }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      shell: bash
      run: |
        aws ecr get-login-password --region us-east-1 | \
        buildah login \
            --username AWS \
            --password-stdin \
            003664043471.dkr.ecr.us-east-1.amazonaws.com
    
    - name: Build and push
      shell: bash
      working-directory: ./testing/node
      env:
        REGISTRY: 003664043471.dkr.ecr.us-east-1.amazonaws.com/virtualnode
      run: |
        buildah bud -f . -t $REGISTRY\:${{ steps.vars_step.outputs.sha-short }} \
        -t $REGISTRY\:${{ steps.vars_step.outputs.branch }}-${{ github.run_number }} \
        -t $REGISTRY\:latest .  && \
        buildah push $REGISTRY\:${{ steps.vars_step.outputs.branch }}-${{ github.run_number }} && \
        buildah push $REGISTRY\:${{ steps.vars_step.outputs.sha-short }} && \
        buildah push $REGISTRY\:latest
    
