name: Update documention
on:
  push:   
    paths:
        - "systems/auth/**"
        - ".github/workflows/theneo.yaml"
jobs:
  update-doc:
    name: update theneo doc
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: process documentation on server
        uses: Theneo-Inc/api-documentation@1.1.1
        with:
          PATH: systems/auth/api-gateway/swagger.yml
          PROJECT_KEY: ${{secrets.PROJECT_KEY}}
          SECRET: ${{secrets.SECRET}}
